- README.txt
Removing modification of READMe in my fork.
> restoring READMe.txt

- src/main/webapp/WEB-INF/pages/main_new.jsp
- src/main/webapp/css/main.css
- src/main/webapp/js/goatApp/controller/LessonController.js
- src/main/webapp/js/goatApp/controller/MenuController.js
- src/main/webapp/js/goatApp/model/HTMLContentModel.js
- src/main/webapp/js/goatApp/model/LessonHintCollection.js
- src/main/webapp/js/goatApp/model/LessonPlanModel.js
- src/main/webapp/js/goatApp/model/LessonSolutionModel.js
- src/main/webapp/js/goatApp/model/LessonSourceModel.js
- src/main/webapp/js/goatApp/support/GoatUtils.js
- src/main/webapp/js/goatApp/view/GoatRouter.js
- src/main/webapp/js/goatApp/view/HelpControlsView.js
- src/main/webapp/js/goatApp/view/LessonContentView.js
- src/main/webapp/js/goatApp/view/LessonHintView.js
- src/main/webapp/js/goatApp/view/MenuView.js
lesson/stage status re-implemented, hints working along with restart lesson. Menu update needs to be re-hooked again. Cookies and Params view and some more testing/clean up.
> Incremental UI changes

- webgoat-container/src/main/webapp/WEB-INF/pages/main_new.jsp
- webgoat-container/src/main/webapp/css/main.css
- webgoat-container/src/main/webapp/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/webapp/js/goatApp/model/LessonCookieCollection.js
- webgoat-container/src/main/webapp/js/goatApp/model/LessonCookieModel.js
- webgoat-container/src/main/webapp/js/goatApp/view/CookieView.js
Params up next and some clean up on menu and other items
> cookie view re-enabled

- webgoat-container/src/main/webapp/css/main.css
- webgoat-container/src/main/webapp/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/webapp/js/goatApp/model/ParamModel.js
- webgoat-container/src/main/webapp/js/goatApp/view/CookieView.js
- webgoat-container/src/main/webapp/js/goatApp/view/ParamView.js
> initial cut of paramView re-enabled

- README.MD
- webgoat_developer_bootstrap.sh
1. Removed the __$__ character from code blocks, making it easier to copy and paste.
2. Fixed instructions regarding how to copy lessons into webgoat-container so they can be added into the package
3. Created a __webgoat_developer_bootstrap.sh__ script to facilitate on-boarding developers trying to use WebGoat
> Improved README, fixed copy lessons instructions, added developer bootstrap

- webgoat-container/src/main/webapp/js/goatApp/view/CookieView.js
- webgoat-container/src/main/webapp/js/goatApp/view/LessonContentView.js
- webgoat-container/src/main/webapp/js/goatApp/view/MenuView.js
Was indeed a victim of some of the js clean-up. Was able to reproduce and able to get lessons running via ReadMe instructions afterward (mvn tomcat7:run-war).
> Fixes for issue #32 - lessons/menu not loading

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/AbstractLesson.java
- webgoat-container/src/main/java/org/owasp/webgoat/service/LessonMenuService.java
- webgoat-container/src/main/webapp/css/main.css
- webgoat-container/src/main/webapp/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/webapp/js/goatApp/controller/MenuController.js
- webgoat-container/src/main/webapp/js/goatApp/model/LessonContentModel.js
- webgoat-container/src/main/webapp/js/goatApp/model/MenuCollection.js
- webgoat-container/src/main/webapp/js/goatApp/model/MenuData.js
- webgoat-container/src/main/webapp/js/goatApp/view/GoatRouter.js
- webgoat-container/src/main/webapp/js/goatApp/view/MenuView.js
- webgoat-container/src/main/webapp/js/goatApp/view/ParamView.js
For issues #22 and #42 (menu reload to update status & support for stage parameter in client-side routing)
> menu and routing work

- .gitignore
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginsLoader.java
- webgoat-container/src/main/java/org/owasp/webgoat/session/WebSession.java
- webgoat-container/src/main/java/org/owasp/webgoat/util/LabelProvider.java
Initial speed up:
before: 5 seconds
now: 2 seconds
> Increase performance while extracting the plugins

- webgoat-container/src/main/java/org/owasp/webgoat/plugins/Plugin.java
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginExtractor.java
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginsLoader.java
- webgoat-container/src/main/java/org/owasp/webgoat/util/LabelProvider.java
- webgoat-container/src/test/java/org/owasp/webgoat/plugins/WebGoatIT.java
Fix for https://github.com/WebGoat/WebGoat/issues/71
> Property files are now detected while extracting the plugin

- webgoat-container/src/main/java/org/owasp/webgoat/plugins/Plugin.java
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginBackgroundLoader.java
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginExtractor.java
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginFileUtils.java
- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginsLoader.java
- webgoat-container/src/main/java/org/owasp/webgoat/util/LabelProvider.java
- webgoat-container/src/test/java/org/owasp/webgoat/plugins/WebGoatIT.java
- webgoat-container/src/test/java/org/owasp/webgoat/util/LabelProviderTest.java
Fixed errors while testing/loading plugins
>  Intermittent Startup Error #71 

- webgoat-container/src/main/java/org/owasp/webgoat/HammerHead.java
> #72, defaulting to firstLesson on initial redirect

- .travis.yml
Coverity isCloud Static Code Analysis service, free for Open-Source projects.
Adding Travis integration with Coverity for automated SCA scaning
> Adding Coverity Static Code Analysis Scan integration

- webgoat-container/src/main/java/org/owasp/webgoat/plugins/PluginExtractor.java
- webgoat-container/src/main/java/org/owasp/webgoat/util/LabelProvider.java
When merging @nbaars fixes yesterday, so of his changes were squashed, breaking the build.
Committing the file now as Nanne intended.
> Fixing inconsistent merge issues implementing nbaars fixes

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/model/LessonInfoModel.java
- webgoat-container/src/main/java/org/owasp/webgoat/lessons/model/LessonMenuItem.java
- webgoat-container/src/main/java/org/owasp/webgoat/service/LessonInfoService.java
- webgoat-container/src/main/java/org/owasp/webgoat/service/LessonMenuService.java
- webgoat-container/src/main/webapp/WEB-INF/pages/main_new.jsp
- webgoat-container/src/main/webapp/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/webapp/js/goatApp/controller/MenuController.js
- webgoat-container/src/main/webapp/js/goatApp/model/LessonContentModel.js
- webgoat-container/src/main/webapp/js/goatApp/model/LessonInfoModel.js
- webgoat-container/src/main/webapp/js/goatApp/view/GoatRouter.js
- webgoat-container/src/main/webapp/js/goatApp/view/TitleView.js
- webgoat-container/src/main/webapp/js/libs/text.js
- webgoat-container/src/main/webapp/js/main.js
More to do, but this will work better for current release. Back/forward buttons will now work with title. Removes kluginess for determining which buttons to show up top.
> #23, #24 - LessonInfo Service now used for TitleView and HelpControsView

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/model/LessonInfoModel.java
- webgoat-container/src/main/java/org/owasp/webgoat/service/HintService.java
Controls to not provide hints from service, nor display them for a Category.CHALLENGE lesson.
> #97, Hint controls for CHALLENGE Category lessons

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/model/LessonInfoModel.java
… in challenge roles. Included plans and solutions along with source and hints.
> #97, updating controls for hints, source, solution and plans on lessons

- README.MD
- webgoat-container/pom.xml
- webgoat-container/src/main/java/org/owasp/webgoat/service/LabelDebugService.java
- webgoat-container/src/main/java/org/owasp/webgoat/session/LabelDebugger.java
- webgoat-container/src/main/java/org/owasp/webgoat/util/LabelManagerImpl.java
- webgoat-container/src/main/webapp/WEB-INF/mvc-dispatcher-servlet.xml
First implementation of highlighting i18n
>  i8n highlighting #96 

- README.MD
Improved README instructions for Easy Run, adding a website link to check for the last modifified data of the exec-jar
Added links for listing build artificats output and link to our Travis.CI job
> Improved README instructions for Easy Run

- .travis.yml
- README.MD
- pom.xml
- webgoat-container/pom.xml
Adding badges for Coverity, Coveralls and Codacy.
> Adding badges for Coverity, Coveralls and Codacy

- .travis.yml
- pom.xml
- webgoat-container/pom.xml
moving the coverall plugin to the parent pom level
> Coveralls should be on Parent Pom

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/AbstractLesson.java
- webgoat-container/src/main/webapp/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/webapp/js/goatApp/model/LessonContentModel.js
- webgoat-container/src/main/webapp/js/goatApp/view/GoatRouter.js
- webgoat-container/src/main/webapp/js/goatApp/view/LessonContentView.js
- webgoat-container/src/main/webapp/main.jsp
- webgoat-container/src/test/java/org/owasp/webgoat/lessons/AbstractLessonTest.java
> Tidy up CSRF lessons.

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/AbstractLesson.java
- webgoat-container/src/main/java/org/owasp/webgoat/lessons/LessonAdapter.java
- webgoat-container/src/main/java/org/owasp/webgoat/lessons/model/LessonInfoModel.java
- webgoat-container/src/test/java/org/owasp/webgoat/lessons/AbstractLessonTest.java
Implements the server-side code to support for the fix being implemented for #144
> #165 support for custom submitMethod

- webgoat_developer_bootstrap.sh
Improved the Developer Bootstratp script to perform some checking for tools and pull the git repo if directory already exists
> Improving WebGoat Developer Bootstrap Script

- webgoat-container/src/main/webapp/WEB-INF/webgoat.properties
Disabling this lesson until #176 is fixed.
> Disable cross-site scripting lab

- webgoat-container/src/main/java/org/owasp/webgoat/session/WebSession.java
- webgoat-container/src/main/webapp/WEB-INF/webgoat.properties
so that we do not reset the stage and recreate the database in the middle of a lesson. To do this a small refactor of WebSession was made which simply extracts some methods from the previously large update method. Ref #176.
> Add stage parameter in the session to keep track of current stage 

- README.MD
Update easy run links to package 7.0.1 and update developer references from 7.0-SNAPSHOT to 7.1-SNAPSHOT as noted by @diegochavezcarro in #200
> Update package references in readme

- webgoat-container/src/main/java/org/owasp/webgoat/Catcher.java
- webgoat-container/src/main/java/org/owasp/webgoat/HammerHead.java
- webgoat-container/src/main/java/org/owasp/webgoat/application/WebGoatServletListener.java
- webgoat-container/src/main/java/org/owasp/webgoat/session/ParameterParser.java
-- Remove unused variable and unused imports.
> -- Remove raw type usage, add type check parameter.

- webgoat-container/src/main/webapp/WEB-INF/pages/main_new.jsp
Load welcome.mvc instead of start.mvc when navigating home on the logo, fixes #218
> Fix broken start/home link on logo

- webgoat-container/src/main/java/org/owasp/webgoat/session/LabelDebugger.java
Removed null checking in favor of boolean which is explicitly value based.
> Remove Exception from method signature

- webgoat-container/src/test/java/org/owasp/webgoat/session/LabelDebuggerTest.java
Code edited in the browser, please run tests ;)
> Code cleanup using @Test(expected = Exception)

- webgoat-images/vagrant-users/Vagrantfile
Add configuration so that VMware fusion configuration matches Virtualbox
> Add VMware fusion

- webgoat-images/vagrant-developers/Vagrantfile
- webgoat-images/vagrant-users/Vagrantfile
- webgoat-images/vagrant_provision.sh
Fixes issue #262 hopefully but also depends on #247 and #281 to be able to test properly.
> Fix intellij link and use master branch for vagrant images

- webgoat-container/src/main/java/org/owasp/webgoat/service/ReportCardService.java
- webgoat-container/src/main/java/org/owasp/webgoat/session/Course.java
- webgoat-container/src/main/java/org/owasp/webgoat/session/UserTracker.java
- webgoat-container/src/main/resources/application.properties
- webgoat-container/src/main/resources/static/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/resources/static/js/goatApp/controller/MenuController.js
- webgoat-container/src/main/resources/static/js/goatApp/model/ReportCardModel.js
- webgoat-container/src/main/resources/static/js/goatApp/templates/report_card.html
- webgoat-container/src/main/resources/static/js/goatApp/view/GoatRouter.js
- webgoat-container/src/main/resources/static/js/goatApp/view/ReportCardView.js
- webgoat-container/src/main/resources/static/js/main.js
- webgoat-container/src/main/resources/templates/main_new.html
- webgoat-container/src/test/java/org/owasp/webgoat/service/ReportCardServiceTest.java
- webgoat-container/src/test/java/org/owasp/webgoat/session/UserTrackerTest.java
- Report card functionality is back
>  #277 Re-institute admin functionality for WebGoat 8

- webgoat-container/src/main/java/org/owasp/webgoat/WebGoat.java
Added config to turn off httpOnly on cookies for #309. Stolen directly from stackoverlfow ...
http://stackoverflow.com/questions/22428233/turn-off-httponly-spring-boot#24187905
> turning off HttpOnly

- webgoat-container/src/main/resources/templates/login.html
In login page each usage made by thymeleaf but logo usage is pageContext.request.contextPath. So i change it to thymeleaf th:href.
> Add Thymeleaf th:href usage instead of pageContext.request.contextPath

- webgoat-container/src/main/java/org/owasp/webgoat/AsciiDoctorTemplateResolver.java
- webgoat-container/src/main/java/org/owasp/webgoat/MvcConfiguration.java
- webgoat-container/src/main/java/org/owasp/webgoat/i18n/Language.java
- webgoat-container/src/main/java/org/owasp/webgoat/i18n/PluginMessages.java
- webgoat-container/src/main/resources/application.properties
- webgoat-container/src/test/java/org/owasp/webgoat/assignments/AssignmentEndpointTest.java
- webgoat-lessons/http-basics/src/main/resources/plugin/HttpBasics/lessonPlans/nl/HttpBasics_content1.adoc
- webgoat-lessons/pom.xml
> Provide Server-side service to support UI localization #265

- webgoat-container/src/main/java/org/owasp/webgoat/AsciiDoctorTemplateResolver.java
- webgoat-container/src/main/java/org/owasp/webgoat/MvcConfiguration.java
- webgoat-container/src/main/java/org/owasp/webgoat/i18n/Language.java
- webgoat-container/src/main/java/org/owasp/webgoat/i18n/PluginMessages.java
- webgoat-container/src/main/resources/application.properties
- webgoat-container/src/test/java/org/owasp/webgoat/assignments/AssignmentEndpointTest.java
- webgoat-lessons/http-basics/src/main/resources/plugin/HttpBasics/lessonPlans/nl/HttpBasics_content1.adoc
- webgoat-lessons/http-proxies/src/main/java/org/owasp/webgoat/plugin/HttpBasicsInterceptRequest.java
- webgoat-lessons/http-proxies/src/main/resources/plugin/HttpProxies/html/HttpProxies.html
Wrong path in in the http request for the http proxies lesson.
Also changed code in the corresponding java file to avoid using methods on null objects
> Fix path httpproxies

- README.MD
Providing instructions on how to change listening IP address.
> Update to README.MD

- webgoat-images/vagrant_provision.sh
Update Vagrant provisioning to use current java 8 Version with updated link.
Solves #385
> Update Java Version

- webgoat-container/src/main/resources/static/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/resources/static/js/goatApp/view/HintView.js
Fix for 'Show Hints' button showing up on initial page load when it shouldn't.
> more hints/helps cleanup

- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/plugin/ContentTypeAssignment.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/plugin/SimpleXXE.java
Thanks to nbaars to helping me out with this. 
Changed a few things the listed .java files to get the testing to work on MacOSX
> fixed ContentTypeAssignment and SimpleXXE to work with MacOSX

- webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content8.adoc
- webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_editOtherProfile.adoc
- webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_inputAltPath.adoc
- webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_intro.adoc
- webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_login.adoc
- webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_mitigation.adoc
- webgoat-lessons/webgoat-introduction/src/main/resources/lessonPlans/en/Introduction.adoc
> Fixed typos

- webgoat-container/src/main/resources/static/js/goatApp/controller/LessonController.js
- webgoat-container/src/main/resources/static/js/goatApp/view/HintView.js
This resets the index to the first hint when the page is changed and fixes the label of the 'Show hints' button after being clicked.
> Fix minor issues in hint view

- webgoat-lessons/jwt/src/main/resources/lessonPlans/en/JWT_refresh.adoc
This PR contains spelling fixes for the JWT lesson
> Fix spelling in JWT lesson

- webgoat-container/src/main/java/org/owasp/webgoat/users/UserForm.java
- webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/plugin/CSRFFeedback.java
- webgoat-lessons/csrf/src/test/java/org/owasp/webgoat/plugin/CSRFFeedbackTest.java
This fixes issues #475 and #476
> Fix crsf lesson

- webgoat-container/src/main/java/org/owasp/webgoat/session/CreateDB.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionLesson6a.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionLesson6b.java
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content6a.adoc
- webgoat-lessons/sql-injection/src/test/java/org/owasp/webgoat/plugin/introduction/SqlInjectionLesson6aTest.java
- webgoat-lessons/sql-injection/src/test/java/org/owasp/webgoat/plugin/introduction/SqlInjectionLesson6bTest.java
This PR contains two fixes for the lessons about SQL injections
> Fix sql injection

- webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content6a.adoc
- webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content6b.adoc
- webgoat-lessons/csrf/src/main/resources/html/CSRF.html
- webgoat-lessons/jwt/src/main/java/org/owasp/webgoat/plugin/JWTVotesEndpoint.java
This PR contains text improvements for the lesson about XSS and two small fixes
> Small lesson improvements

- webgoat-lessons/csrf/src/main/resources/lessonPlans/en/CSRF_Login.adoc
This improves the explanation of the lesson about CSRF
> Improve text for lesson about CSRF login

- webgoat-images/vagrant-training/Vagrantfile
- Added correct wget urls for .jar files
- changed server address to 0.0.0.0(pointing to all interfaces) because by default it listens for connections on VM's localhost only but we want to access webgoat on NAT adapter via port forwarding
> Fixed Vagrant file

- docker-compose-postgres.yml
The structure of the environment was incorrect. The postgres dialect doesn't match the postgres:latest image.
> YAML structure fix, postgres version fix

- webgoat-lessons/sql-injection/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/sql-injection/src/test/java/org/owasp/webgoat/plugin/introduction/SqlInjectionLesson5aTest.java
"You have succeed" → "You have succeeded" in SQLI lesson.
> Fix a grammatical error

- webgoat-lessons/http-proxies/src/main/resources/lessonPlans/en/HttpBasics_ProxyIntro1.adoc
- webgoat-lessons/webwolf-introduction/src/main/resources/lessonPlans/en/IntroductionWebWolf.adoc
- webgoat-lessons/webwolf-introduction/src/main/resources/lessonPlans/en/Landing_page.adoc
- webgoat-lessons/webwolf-introduction/src/main/resources/lessonPlans/en/Receiving_mail.adoc
- webgoat-lessons/webwolf-introduction/src/main/resources/lessonPlans/en/Uploading_files.adoc
Made some changes to improve the language, so the introduction is easier to understand.
> Improve language and readability

- webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/plugin/SimpleMailAssignment.java
Small typo fix in Simple e-mail assignment message
> Fix simple email assignment typo

- webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/plugin/SimpleMailAssignment.java
- webwolf/src/main/java/org/owasp/webwolf/user/UserService.java
- webwolf/src/test/java/org/owasp/webwolf/user/UserServiceTest.java
Adding some test coverage around WebWolf UserService
Remove @AllArgsConstructor from UserService to enable unit testing(Could not test this class with the AllArgs annotation)
> Add user service tests

- webgoat-container/src/main/java/org/owasp/webgoat/MvcConfiguration.java
- webgoat-lessons/secure-passwords/src/main/java/org/owasp/webgoat/plugin/SecurePasswordsAssignment.java
- webgoat-lessons/secure-passwords/src/main/resources/html/SecurePasswords.html
- webgoat-lessons/secure-passwords/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/secure-passwords/src/main/resources/i18n/WebGoatLabels_nl.properties
> Secure password hidden

- README.MD
Small improvement to the project's readme.
Took me way too much time to figure these out :)
> Add links to landing pages

- webgoat-lessons/webwolf-introduction/src/main/resources/html/WebWolfIntroduction.html
A small annoyance was there in the WebWolf Introduction. the exercise item 3 with the send email assignment, would never show the green completed button. It has to do with two attack form elements.
One is used to give feedback on sending the mail and one is used for checking the value.
By changing the order of the form elements in the html, the task will show green when completed.
> webwolf intro assignment 3 green button fix

- webgoat-lessons/xxe/src/test/java/org/owasp/webgoat/plugin/BlindSendFileAssignmentTest.java
Simple fix for Issue #585  (Test failure in XXE (German output compared with English output fails)).
> fixed test

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/Category.java
- webgoat-lessons/pom.xml
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/plugin/XXE.java
Restructured the menu so it is easily related to the OWASP top 10 categories.
See #591 for a screenshot
Also corrected the relative path in webgoat-lessons/pom.xml #566
> Owasp categories

- webgoat-container/src/main/java/org/owasp/webgoat/MvcConfiguration.java
- webgoat-container/src/main/resources/application.properties
- webgoat-container/src/main/resources/static/css/main.css
- webgoat-lessons/chrome-dev-tools/src/main/java/org/owasp/webgoat/plugin/NetworkDummy.java
- webgoat-lessons/chrome-dev-tools/src/main/java/org/owasp/webgoat/plugin/NetworkLesson.java
- webgoat-lessons/chrome-dev-tools/src/main/resources/html/ChromeDevTools.html
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionChallenge.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionChallengeLogin.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionLesson6a.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionLesson6b.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionQuiz.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/Servers.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson10a.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson10b.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson12a.java
- webgoat-lessons/sql-injection/src/main/resources/html/SqlInjection.html
- webgoat-lessons/sql-injection/src/main/resources/html/SqlInjectionAdvanced.html
- webgoat-lessons/sql-injection/src/main/resources/html/SqlInjectionMitigations.html
- webgoat-lessons/sql-injection/src/test/java/org/owasp/webgoat/plugin/introduction/SqlInjectionLesson6aTest.java
- webgoat-lessons/sql-injection/src/test/java/org/owasp/webgoat/plugin/introduction/SqlInjectionLesson6bTest.java
- webgoat-lessons/sql-injection/src/test/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson12aTest.java
- webwolf/src/main/resources/application.properties
This branch is meant to fix a number of bugs related to the "progress" of exercises and some other UI related elements that needed some change.
In this commit the progress of chrome developer tool lessons is fixed and the form fields for sql injection is enlarged.
> increased sql form fields and fixed chrome progress

- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionChallenge.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/advanced/SqlInjectionChallengeLogin.java
- webgoat-server/src/test/java/org/owasp/webgoat/SqlInjectionAdvanced_TestHelper.java
- webgoat-server/src/test/java/org/owasp/webgoat/TestHelper.java
This is meant to solve the same issue as mentioned in #638 .
Altough this one does not contain unintended commits and adds an integration test on the sql advanced test 5 progress.
> fixed sql adv 5 progress and added prove in integration test

- webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/plugin/SimpleMailAssignment.java
- webwolf/src/main/java/org/owasp/webwolf/user/UserService.java
- webwolf/src/test/java/org/owasp/webwolf/user/UserServiceTest.java
- webwolf/src/test/java/org/owasp/webwolf/user/UserValidatorTest.java
Add UserValidator Unit tests. Also added back AllArgs annotation with the discover of '@InjectMocks' :)
> Add user validator tests

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SqlInjectionMitigationTest.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson10a.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson10b.java
- webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson12a.java
- webgoat-lessons/sql-injection/src/main/resources/html/SqlInjectionMitigations.html
Some fixes in path names in order for the lesson completion to work. Including a check in the integration test if all mitigation assignments are completed
> fix for complete progress of sql mitigations and integration test

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/JWTLessonTest.java
- webgoat-lessons/jwt/src/main/java/org/owasp/webgoat/plugin/JWTSecretKeyEndpoint.java
- webgoat-lessons/jwt/src/main/java/org/owasp/webgoat/plugin/JWTVotesEndpoint.java
- webgoat-lessons/jwt/src/main/resources/html/JWT.html
- webgoat-lessons/jwt/src/main/resources/js/jwt-voting.js
- webgoat-lessons/jwt/src/main/resources/lessonPlans/en/JWT_weak_keys
- webgoat-lessons/jwt/src/test/java/org/owasp/webgoat/plugin/JWTVotesEndpointTest.java
The first two challenges have been verified and fixed concerning the green progress bar issue. The challenge for brute force finding the secret has been made a bit more hard by not using one fixed key for that. two integration tests have been added
> fixed and improved first two jwt challenges

- webgoat-container/src/main/resources/application-webgoat.properties
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/XXETest.java
- webgoat-integration-tests/src/test/resources/application-inttest.properties
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/plugin/ContentTypeAssignment.java
Integration test added for XXE assignments. (I tested on Mac, and will still have to do a test on Windows
> XXE tests added 

- webgoat-lessons/webgoat-introduction/src/main/resources/lessonPlans/nl/Introduction.adoc
- webgoat-lessons/webwolf-introduction/src/main/resources/lessonPlans/nl/IntroductionWebWolf.adoc
Dutch doc texts for WebGoat and WebWolf introduction
> Add dutch intro

- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content12.adoc
Fix typo `date` to `data` which seems more appropriate in context.
> Fix typo in SQL Injection(Introduction)

- webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/password_reset/ResetLinkAssignment.java
- webgoat-lessons/password-reset/src/main/resources/templates/password_link_not_found.html
- webgoat-lessons/password-reset/src/main/resources/templates/success.html
Possibly related to moving to @RestController so the views needed some attention. Plain strings were returned in stead of the intended views. Also at least for Firefox <script .../> needed to be changed to <script></script>
> fixed views for password reset

- webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_intro.adoc
- webgoat-lessons/secure-passwords/src/main/resources/lessonPlans/en/SecurePasswords_1.adoc
- A link to passwordping has been fixed
- Links to other relevant OWASP resources have been added
> Proposition for fixing broken/improving links

- pom.xml
[SECURITY] Releases are built/executed/released in the context of insecure/untrusted code #558
> Explicitly set Maven repo to https

- webgoat-images/vagrant-training/Vagrantfile
Don't know if people still like to use this. But it still works and I updated it to JRE11 and latest M25 release
> update JRE and milestone version to latest

- webgoat-container/src/main/resources/templates/about.html
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/CryptoTest.java
- webgoat-lessons/crypto/pom.xml
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/Crypto.java
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/CryptoUtil.java
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/EncodingAssignment.java
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/HashingAssignment.java
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/SecureDefaultsAssignment.java
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/SigningAssignment.java
- webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/XOREncodingAssignment.java
- webgoat-lessons/crypto/src/main/resources/html/Crypto.html
- webgoat-lessons/crypto/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/Crypto_plan.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/defaults.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/encoding_plan.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/encoding_plan2.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/encryption.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/hashing_plan.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/keystores.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/postquantum.adoc
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/signing.adoc
- webgoat-lessons/crypto/src/main/resources/lessonSolutions/en/crypto_solution.adoc
- webgoat-lessons/crypto/src/main/resources/lessonSolutions/html/crypto.html
- webgoat-lessons/crypto/src/test/java/org/owasp/webgoat/crypto/CryptoUtilTest.java
- webgoat-lessons/pom.xml
- webgoat-server/pom.xml
I think there is enough content and assignments in the lesson. So maybe time to be added and see the feedback. The last assignment uses a docker container from docker hub. Perhaps we can put this under the webgoat handle in stead of my own handle. #687
> Crypto lesson

- webgoat-lessons/pom.xml
- webgoat-lessons/vulnerable-components/pom.xml
> Revert "Bump xstream from 1.4.5 to 1.4.6 in /webgoat-lessons"

- webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/csrf/CSRFGetFlag.java
> Fix NPE when request does not contain parameter

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/PasswordResetLessonTest.java
- webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson3.java
- webgoat-lessons/crypto/src/test/java/org/owasp/webgoat/crypto/CryptoUtilTest.java
- webgoat-lessons/idor/src/main/java/org/owasp/webgoat/idor/IDORViewOwnProfile.java
- webgoat-lessons/insecure-deserialization/src/main/java/org/dummy/insecure/framework/VulnerableTaskHolder.java
- webgoat-lessons/jwt/src/main/java/org/owasp/webgoat/jwt/JWTSecretKeyEndpoint.java
- webgoat-lessons/jwt/src/test/java/org/owasp/webgoat/jwt/JWTVotesEndpointTest.java
- webgoat-lessons/jwt/src/test/java/org/owasp/webgoat/jwt/TokenTest.java
- webgoat-lessons/missing-function-ac/src/main/java/org/owasp/webgoat/missing_ac/MissingFunctionACUsers.java
- webwolf/pom.xml
- webwolf/src/test/resources/logback-test.xml
small change to reduce some useless logs in unit tests and build results
> suppressing some useless log messages and banners in unit tests

- webwolf/pom.xml
oops, the suppress logging pull request removed a bit too much for webwolf
> restored pom removal

- webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson5a.java
Allow for content before and after the script; Allow optional semicolon
> relax detection regex

- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/hashing_plan.adoc
As explained in a comment from #712 the use of a plain hash is not a good idea, but the use of a salted hash is recommended. I refer to the OWASP cheat sheet as well
> added notes on salted hash

- webgoat-lessons/jwt/src/main/java/org/owasp/webgoat/jwt/JWTFinalEndpoint.java
- webgoat-lessons/jwt/src/main/resources/html/JWT.html
- webgoat-lessons/jwt/src/main/resources/lessonPlans/en/JWT_structure.adoc
- webgoat-lessons/jwt/src/test/java/org/owasp/webgoat/jwt/JWTFinalEndpointTest.java
Because JWT.io does not support alg none anymore, I have refactored page two to include a test which could be used in the assignments
> Jwt util added

- webgoat-lessons/csrf/src/main/resources/lessonPlans/en/CSRF_Impact_Defense.adoc
Fixed broken links on CSRF protections section
> Fixed CSRF broken links.

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/GeneralLessonTest.java
- webgoat-lessons/insecure-login/src/main/resources/html/InsecureLogin.html
- webgoat-lessons/password-reset/src/main/resources/html/PasswordReset.html
- webgoat-lessons/webwolf-introduction/src/main/resources/html/WebWolfIntroduction.html
#789 
Fixes for three places where the button did not change to green after successful completion
> fix green buttons

- webgoat-container/src/main/resources/static/js/libs/ace.js
- webgoat-lessons/cross-site-scripting/src/main/resources/html/CrossSiteScriptingMitigation.html
- webgoat-lessons/sql-injection/src/main/resources/html/SqlInjectionMitigations.html
#791 
Plain js added again and UI becomes visible again
> ace editor added without all the nonsense around it

- webgoat-container/src/main/resources/static/js/libs/mode-java.js
- webgoat-container/src/main/resources/static/js/libs/theme-monokai.js
- webgoat-lessons/webwolf-introduction/src/main/resources/html/WebWolfIntroduction.html
missed two scripts for highlighting in Java style. And corrected WebWolf intro green button as it was not correctly fixed last time
> added ace js for java

- webgoat-container/src/main/java/org/owasp/webgoat/users/Scoreboard.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/ChallengeTest.java
- webgoat-lessons/challenge/src/main/java/org/owasp/webgoat/challenges/Flag.java
#811 #810 are included in this fix.
Also 1 test has been added to verify that it remains ok in upcoming changes
> flag submission fixed

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/ChallengeTest.java
- webgoat-lessons/challenge/src/main/java/org/owasp/webgoat/challenges/challenge1/Assignment1.java
- webgoat-lessons/challenge/src/main/java/org/owasp/webgoat/challenges/challenge1/ImageServlet.java
- webgoat-lessons/challenge/src/main/resources/html/Challenge1.html
- webgoat-lessons/challenge/src/test/java/org/owasp/webgoat/challenges/Assignment1Test.java
- webgoat-server/src/main/java/org/owasp/webgoat/StartWebGoat.java
Small adjustment to challenge1 so people cannot solve it by google only.
> Ch1 less default

- webgoat-lessons/password-reset/src/main/resources/lessonPlans/en/PasswordReset_plan.adoc
> PasswordReset_plan.adoc: Spelling fixes

- docker/Dockerfile
- docker/start.sh
Some adjustments are needed to comply to guidelines for secure containers. 
I came across some areas for improvement while trying to get WebGoat up and running on OpenShift.
See the [blog](https://zubcevicdotcom.wordpress.com/owasp-webgoat/deploying-webgoat-on-openshift/) on the steps in the OpenShift playground and the Redhat docker container guidelines.
> adjustments for arbitrary user support (openshift guideline)

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/ChallengeTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SSRFTest.java
- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/hashing_plan.adoc
- webgoat-lessons/csrf/src/main/resources/lessonPlans/en/CSRF_JSON.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content5_after.adoc
- webgoat-lessons/ssrf/src/main/resources/html/SSRF.html
- webgoat-lessons/ssrf/src/main/resources/lessonPlans/en/SSRF_Intro.adoc
- webgoat-lessons/ssrf/src/main/resources/lessonPlans/en/SSRF_Task1.adoc
- webgoat-lessons/ssrf/src/main/resources/lessonPlans/en/SSRF_Task2.adoc
- webgoat-lessons/vulnerable-components/src/main/resources/html/VulnerableComponents.html
- webgoat-lessons/vulnerable-components/src/main/resources/lessonPlans/en/VulnerableComponents_content4c.adoc
- webgoat-lessons/xxe/src/main/resources/lessonPlans/en/XXE_changing_content_type_solution.adoc
- webgoat-lessons/xxe/src/main/resources/lessonPlans/en/XXE_mitigation.adoc
> Small fixes june 2020

- webgoat-lessons/cia/src/main/resources/js/questions_cia.json
- webgoat-lessons/cia/src/main/resources/lessonPlans/en/CIA_availability.adoc
- webgoat-lessons/cia/src/main/resources/lessonPlans/en/CIA_confidentiality.adoc
- webgoat-lessons/cia/src/main/resources/lessonPlans/en/CIA_integrity.adoc
- webgoat-lessons/cia/src/main/resources/lessonPlans/en/CIA_intro.adoc
- webgoat-lessons/cia/src/main/resources/lessonPlans/en/CIA_quiz.adoc
This pull request corrects a few grammatical issues in the CIA section. I attempted to improve the clarity of the text a bit and a small amount of additional content (i.e. example protection mechanisms).
> Update CIA Content/Questions

- webgoat-container/src/main/resources/static/css/main.css
- webgoat-container/src/main/resources/static/js/application.js
- webgoat-container/src/main/resources/static/js/goatApp/view/MenuView.js
- webgoat-container/src/main/resources/templates/login.html
- webgoat-container/src/main/resources/templates/main_new.html
- webgoat-container/src/main/resources/templates/registration.html
> Ui buttons

- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content8.adoc
Thanks for an excellent learning tool! I got stuck for a minute because a given SQL query was malformed.
> Add missing trailing double quote in sql query

- webgoat-server/src/main/java/org/owasp/webgoat/StartWebGoat.java
- webwolf/src/main/java/org/owasp/webwolf/WebWolf.java
Some checks at startup to make sure that things are started in the right order and give hints what to do when ports are taken
> added start checks with hints on port usage

- pom.xml
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/GeneralLessonTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/IDORTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/JWTLessonTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/PathTraversalTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SqlInjectionMitigationTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/WebWolfTest.java
- webwolf/pom.xml
- webwolf/src/test/java/org/owasp/webwolf/mailbox/MailboxControllerTest.java
- webwolf/src/test/java/org/owasp/webwolf/mailbox/MailboxRepositoryTest.java
- webwolf/src/test/java/org/owasp/webwolf/user/UserServiceTest.java
- webwolf/src/test/java/org/owasp/webwolf/user/UserValidatorTest.java
upgrade to 2.4.0 and fixes for some related unit issues
> upgrade springboot version and some related unit test fixes

- README.MD
Maybe we can try to get more interactions and share ideas with the community using gitter? In that case this badge is a useful link to connect to the gitter environmeng.
> gitter badge

- webgoat-lessons/ssrf/src/main/java/org/owasp/webgoat/ssrf/SSRFTask2.java
temporary fix in case outages of original site occur
> fix in case external site is down

- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content1.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content10.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content11.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content2.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content3.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content4.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content5_after.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content5_before.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content6.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content8.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_content9.adoc
- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_introduction_plan.adoc
This PR corrects some typos/grammar issues and also restructures some sentences for clarity.
> Update SQLi Lesson Text

- webgoat-lessons/crypto/src/main/resources/lessonPlans/en/postquantum.adoc
Fixed a typo in the documentation and added a colon for better readability
> Fixed a typo in postquantum.adoc

- .travis.yml
- webgoat-integration-tests/pom.xml
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SeleniumTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SqlInjectionLessonTest.java
With one extra dependency and one extra test class we can reuse some logic and include a browser headless test. Adjusted the .travis.yml file to add the Firefox web driver and the Firefox browser.
What do you think? added value or not really necessary or do you prefer another type of browser test? It will run on your windows/Mac as well if you have the proper driver installed and the correct path to it. Otherwise the test will be ignored
> Selenium test added

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/ProgressRaceConditionTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SeleniumTest.java
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SqlInjectionLessonTest.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/SimpleXXE.java
I noticed that all integration tests reported 0 run. And noticed that @BeforeAll was changed. This was the root cause.
I disabled to drop column as it is no longer required due to the improved db use
> Fix for accidentally disabled integration tests

- docker/start.sh
- webgoat-lessons/vulnerable-components/src/main/resources/lessonPlans/en/VulnerableComponents_content5a.adoc
> Fix vulnerable components lesson for Java 16.

- webgoat-lessons/jwt/src/main/resources/lessonPlans/en/JWT_libraries_assignment.adoc
Replace `name` with `user` and add `admin`
> #1039: Fix token

- webgoat-container/src/main/java/org/owasp/webgoat/lessons/Category.java
- webgoat-lessons/pom.xml
- webgoat-lessons/spoof-cookie/pom.xml
- webgoat-lessons/spoof-cookie/src/main/java/org/owasp/webgoat/spoofcookie/SpoofCookie.java
- webgoat-lessons/spoof-cookie/src/main/java/org/owasp/webgoat/spoofcookie/SpoofCookieAssignment.java
- webgoat-lessons/spoof-cookie/src/main/java/org/owasp/webgoat/spoofcookie/encoders/EncDec.java
- webgoat-lessons/spoof-cookie/src/main/resources/html/SpoofCookie.html
- webgoat-lessons/spoof-cookie/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/spoof-cookie/src/main/resources/js/handler.js
- webgoat-lessons/spoof-cookie/src/main/resources/lessonPlans/en/SpoofCookie_content0.adoc
- webgoat-lessons/spoof-cookie/src/main/resources/lessonPlans/en/SpoofCookie_plan.adoc
- webgoat-lessons/spoof-cookie/src/main/resources/lessonSolutions/en/SpoofCookie_solution.adoc
- webgoat-lessons/spoof-cookie/src/main/resources/lessonSolutions/html/SpoofCookie.html
- webgoat-lessons/spoof-cookie/src/main/resources/templates/form.html
- webgoat-lessons/spoof-cookie/src/test/java/org/owasp/webgoat/spoofcookie/SpoofCookieAssignmentTest.java
- webgoat-lessons/spoof-cookie/src/test/java/org/owasp/webgoat/spoofcookie/encoders/EncDecTest.java
- webgoat-server/pom.xml
issue: #602
Added new lesson that covers the management flaws: spoofing an authentication cookie lesson contents and objectives.
Edit: I have squashed the PR in one commit.
> feat: session management flaws: spoofing an authentication cookie

- .github/workflows/build.yml
- .github/workflows/quality_checks.yml
- .github/workflows/rebase.yml
- .github/workflows/release.yml
- .github/workflows/welcome.yml
- pom.xml
Innoday contrib 1: adding an on push quality check before contributing other things.
> Innoday contrib

- webgoat-lessons/jwt/src/main/java/org/owasp/webgoat/jwt/JWTSecretKeyEndpoint.java
- webgoat-lessons/jwt/src/test/java/org/owasp/webgoat/jwt/JWTSecretKeyEndpointTest.java
> fix: token signature validation

- .github/FUNDING.yml
- .github/lock.yml
- .github/stale.yml
- CODE_OF_CONDUCT.md
- Added funding link
- Added code of conduct
- Added locking and stalling as from https://github.com/juice-shop/juice-shop
> Xebia innovation day contrib 2

- .github/FUNDING.yml
- .github/lock.yml
- .github/stale.yml
- .github/workflows/signoff_mr.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- README.MD
This is an MR with the following changes:
- Added a funding link (As the OMTG team did at https://github.com/OWASP/owasp-mstg)
- Added Code of conduct, Contributing, and PR template based on https://github.com/juice-shop/juice-shop,  https://github.com/OWASP/owasp-mstg, and https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md
- added lock and stale files based on https://github.com/juice-shop/juice-shop
- added signoff script from https://github.com/JasonEtco/signoff-commit-action
Thank you @bkimminich and @JasonEtco for the inspiration!
This issue closes https://github.com/WebGoat/WebGoat/issues/1028
> Xebia innovation day contribution 2

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
Signed-off-by: Jeroen Willemsen <jwillemsen@xebia.com>
Thank you for submitting a Pull Request to the WebGoat. Please make sure that:
If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.
> Update sign off command

- README.MD
This PR updates the JDK version references.
> Update JDK references

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/XSSTest.java
- webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson1.java
- webgoat-lessons/cross-site-scripting/src/main/resources/html/CrossSiteScripting.html
- webgoat-lessons/cross-site-scripting/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content1.adoc
- webgoat-lessons/cross-site-scripting/src/test/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson1Test.java
Improved the XSS Lesson 1 with a boolean response.
This PR closes #840.
> Boolean response for XSS Lesson 1

- webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content7.adoc
Thank you for submitting a Pull Request to the WebGoat. Please make sure that:
If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.
> 1101: fix quoting in statement

- README.MD
Thank you for submitting a Pull Request to the WebGoat. Please make sure that:
> Fix for badge

- .github/workflows/branch_build.yml
- .github/workflows/pr_build.yml
- CREATE_RELEASE.MD
> Rename master to main

- webgoat-lessons/insecure-login/src/main/java/org/owasp/webgoat/insecure_login/InsecureLoginTask.java
- webgoat-lessons/insecure-login/src/main/resources/js/credentials.js
- webgoat-lessons/insecure-login/src/main/resources/lessonPlans/en/InsecureLogin_Intro.adoc
- webgoat-lessons/insecure-login/src/main/resources/lessonPlans/en/InsecureLogin_Task.adoc
The JavaScript posts to a random endpoint resulting in a HTTP/405 we now post to an existing endpoint.
Resolves: #1142
> Add endpoint for the JavaScript to post to

- README.MD
> Fix to move to java17

- README.MD
> Fix readme 2

- README.MD
> Add Discussions badge

- webgoat-integration-tests/src/test/java/org/owasp/webgoat/SessionManagementTest.java
- webgoat-lessons/hijack-session/pom.xml
- webgoat-lessons/hijack-session/src/main/java/org/owasp/webgoat/hijacksession/HijackSession.java
- webgoat-lessons/hijack-session/src/main/java/org/owasp/webgoat/hijacksession/HijackSessionAssignment.java
- webgoat-lessons/hijack-session/src/main/java/org/owasp/webgoat/hijacksession/cas/Authentication.java
- webgoat-lessons/hijack-session/src/main/java/org/owasp/webgoat/hijacksession/cas/AuthenticationProvider.java
- webgoat-lessons/hijack-session/src/main/java/org/owasp/webgoat/hijacksession/cas/HijackSessionAuthenticationProvider.java
- webgoat-lessons/hijack-session/src/main/resources/html/HijackSession.html
- webgoat-lessons/hijack-session/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/hijack-session/src/main/resources/lessonPlans/en/HijackSession_content0.adoc
- webgoat-lessons/hijack-session/src/main/resources/lessonPlans/en/HijackSession_plan.adoc
- webgoat-lessons/hijack-session/src/main/resources/lessonSolutions/en/HijackSession_solution.adoc
- webgoat-lessons/hijack-session/src/main/resources/lessonSolutions/html/HijackSession.html
- webgoat-lessons/hijack-session/src/main/resources/templates/hijackform.html
- webgoat-lessons/hijack-session/src/test/java/org/owasp/webgoat/hijacksession/HijackSessionAssignmentTest.java
- webgoat-lessons/hijack-session/src/test/java/org/owasp/webgoat/hijacksession/cas/HijackSessionAuthenticationProviderTest.java
- webgoat-lessons/pom.xml
- webgoat-server/pom.xml
> Hijack session conflict

- RELEASE_NOTES.md
- docker/Dockerfile
- docker/start.sh
- Make sure the last line contains the information
- Split in separate functions
- Add option to skip starting nginx (by default it is started)
> Improve Docker start up script

- webgoat-lessons/path-traversal/src/main/resources/i18n/WebGoatLabels.properties
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_intro.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_retrieval.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_upload.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_upload_fix.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_upload_fixed.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_upload_mitigation.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_upload_remove_user_input.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_zip_slip.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_zip_slip_assignment.adoc
- webgoat-lessons/path-traversal/src/main/resources/lessonPlans/en/PathTraversal_zip_slip_solution.adoc
> Update the documentation

- .github/workflows/branch_build.yml
- .github/workflows/pr_build.yml
- .github/workflows/release.yml
- pom.xml
- webgoat-container/src/main/java/org/owasp/webgoat/service/SessionService.java
- webgoat-container/src/main/java/org/owasp/webgoat/session/WebSession.java
- webgoat-container/src/main/resources/i18n/messages.properties
- webgoat-integration-tests/src/test/java/org/owasp/webgoat/XXETest.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/BlindSendFileAssignment.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/Comments.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/ContentTypeAssignment.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/SimpleXXE.java
- webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/User.java
- webgoat-lessons/xxe/src/main/resources/html/XXE.html
We can use it for more lessons and showcase how to apply security directly from the source code.
Resolves: #1176
> Move enabling security to WebGoat core and add resetting the lessons.

- pom.xml
- webgoat-container/pom.xml
- webgoat-container/src/test/java/org/owasp/webgoat/users/UserValidatorTest.java
- webgoat-lessons/client-side-filtering/src/main/java/org/owasp/webgoat/client_side_filtering/ShopEndpoint.java
- webwolf/pom.xml
> upgrade to latest spring-boot libs and fixed related issues

- README.md
Fixes the build link and badge.
> Fix Build Badge and Link

- pom.xml
> update spring boot

- src/main/java/org/owasp/webgoat/container/lessons/Category.java
- src/main/java/org/owasp/webgoat/lessons/auth_bypass/AuthBypass.java
- src/main/java/org/owasp/webgoat/lessons/cryptography/Cryptography.java
- src/main/java/org/owasp/webgoat/lessons/csrf/CSRF.java
- src/main/java/org/owasp/webgoat/lessons/deserialization/InsecureDeserialization.java
- src/main/java/org/owasp/webgoat/lessons/hijacksession/HijackSession.java
- src/main/java/org/owasp/webgoat/lessons/idor/IDOR.java
- src/main/java/org/owasp/webgoat/lessons/insecure_login/InsecureLogin.java
- src/main/java/org/owasp/webgoat/lessons/jwt/JWT.java
- src/main/java/org/owasp/webgoat/lessons/logging/LogSpoofing.java
- src/main/java/org/owasp/webgoat/lessons/missing_ac/MissingFunctionAC.java
- src/main/java/org/owasp/webgoat/lessons/password_reset/PasswordReset.java
- src/main/java/org/owasp/webgoat/lessons/path_traversal/PathTraversal.java
- src/main/java/org/owasp/webgoat/lessons/secure_passwords/SecurePasswords.java
- src/main/java/org/owasp/webgoat/lessons/spoofcookie/SpoofCookie.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/advanced/SqlInjectionAdvanced.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjection.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/mitigation/SqlInjectionMitigations.java
- src/main/java/org/owasp/webgoat/lessons/ssrf/SSRF.java
- src/main/java/org/owasp/webgoat/lessons/vulnerable_components/VulnerableComponents.java
- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScripting.java
- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScriptingMitigation.java
- src/main/java/org/owasp/webgoat/lessons/xss/stored/CrossSiteScriptingStored.java
- src/main/java/org/owasp/webgoat/lessons/xxe/XXE.java
- src/test/java/org/owasp/webgoat/container/service/LessonMenuServiceTest.java
- src/test/java/org/owasp/webgoat/container/users/UserTrackerRepositoryTest.java
- src/test/java/org/owasp/webgoat/lessons/vulnerable_components/VulnerableComponentsLessonTest.java
Reshuffling the lessons to match the new top 10.
See https://owasp.org/www-project-top-ten/ 
#1093
> owasp top10-2021

- src/main/resources/lessons/jwt/documentation/JWT_libraries_assignment.adoc
> JWT doc code typo fix

- src/main/resources/webgoat/static/css/main.css
- src/main/resources/webgoat/templates/about.html
I added myself as active developer in the about page.
This PR also fixes the footer overlapping on the same page; fixes the horizontal line in the middle of the document . See attached pictures of the issue.
> Added myself as active developer and footer fix

- pom.xml
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge7/MD5.java
- src/main/java/org/owasp/webgoat/lessons/client_side_filtering/Salaries.java
- src/main/java/org/owasp/webgoat/lessons/secure_passwords/SecurePasswordsAssignment.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/advanced/SqlInjectionLesson6a.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson10.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson2.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson3.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson4.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson5b.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson8.java
- src/main/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson9.java
- src/main/java/org/owasp/webgoat/lessons/ssrf/SSRFTask1.java
- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScriptingLesson5a.java
- src/main/resources/lessons/client_side_filtering/lessonSolutions/en/ClientSideFiltering.html
- src/main/resources/webgoat/static/js/libs/mode-java.js
- src/main/resources/webgoat/static/js/libs/text.js
> Some updates and code improvements

- config/dependency-check/project-suppression.xml
- pom.xml
- src/main/java/org/owasp/webgoat/lessons/sql_injection/advanced/SqlInjectionLesson6a.java
- src/test/java/org/owasp/webgoat/lessons/sql_injection/introduction/SqlInjectionLesson6aTest.java
> Pom update

- pom.xml
- src/main/java/org/owasp/webgoat/lessons/csrf/ForgedReviews.java
- src/main/java/org/owasp/webgoat/lessons/xss/stored/StoredXssComments.java
- src/main/java/org/owasp/webgoat/lessons/xxe/CommentsCache.java
> joda time refactored some dep fix

- src/it/java/org/owasp/webgoat/LabelAndHintIntegrationTest.java
> hints tested

- src/main/resources/lessons/path_traversal/documentation/PathTraversal_upload.adoc
- src/main/resources/lessons/path_traversal/documentation/PathTraversal_upload_fix.adoc
- src/main/resources/lessons/path_traversal/documentation/PathTraversal_upload_remove_user_input.adoc
- src/main/resources/lessons/path_traversal/documentation/PathTraversal_zip_slip_assignment.adoc
> Fixes #1233 - Path traversal seems to contain wrong description

- .github/workflows/test.yml
> Workflow fix

- src/main/resources/lessons/webgoat_introduction/documentation/Introduction_fr.adoc
- src/main/resources/webgoat/templates/main_new.html
There was one issue due to having two dropdowns. This fixes the issue.
> fix in style sheet that now shows normal dropdown behaviour

- src/main/resources/i18n/messages.properties
- src/main/resources/webgoat/static/js/search.js
- src/main/resources/webgoat/templates/main_new.html
A working version with a search box which will select a matching menu item upon submit. It can be nicer in case you search and find something in the same category, but this is the best I can deliver.
> search the menu using input box

- src/main/java/org/owasp/webgoat/container/AsciiDoctorTemplateResolver.java
- src/main/java/org/owasp/webgoat/container/MvcConfiguration.java
> isReadable works inside a container, isFile not

- src/main/java/org/owasp/webgoat/lessons/passwordreset/SecurityQuestionAssignment.java
while "wear" and "were" have similar pronunciation, one of them is better here than the other :)
> Fixed incorrect word

- README.md
Fixes: #1264 
Added information on the step to be followed after local setup.
> Added info about login in the ReadMe file

- .gitignore
- src/main/resources/lessons/sqlinjection/documentation/SqlInjection_challenge.adoc
- src/main/resources/lessons/sqlinjection/documentation/SqlInjection_content9.adoc
> Add sql lesson

- src/main/resources/lessons/webwolfintroduction/documentation/IntroductionWebWolf.adoc
- src/main/resources/lessons/webwolfintroduction/documentation/Landing_page.adoc
- src/main/resources/lessons/webwolfintroduction/documentation/Receiving_mail.adoc
- src/main/resources/lessons/webwolfintroduction/documentation/Uploading_files.adoc
- Add reference to the WebWolf icon in the top right corner.
- Format all text of the lesson
> Update the WebWolf lesson 

- src/main/java/org/owasp/webgoat/lessons/pathtraversal/ProfileUploadBase.java
- src/main/java/org/owasp/webgoat/lessons/pathtraversal/ProfileZipSlip.java
- src/main/resources/lessons/pathtraversal/documentation/PathTraversal_zip_slip_assignment.adoc
- src/main/resources/lessons/pathtraversal/documentation/PathTraversal_zip_slip_solution.adoc
- src/main/resources/lessons/pathtraversal/html/PathTraversal.html
> Update the Zip Slip assignment

- src/main/resources/lessons/pathtraversal/js/path_traversal.js
> Remove unused JavaScript function

- src/main/java/org/owasp/webgoat/container/lessons/Category.java
- src/main/java/org/owasp/webgoat/lessons/xxe/XXE.java
- src/main/resources/lessons/xxe/html/XXE.html
> Move XXE to A05 - Security Misconfiguration

- pom.xml
- src/main/java/org/owasp/webgoat/lessons/passwordreset/ResetLinkAssignment.java
- src/test/java/org/owasp/webgoat/container/plugins/LessonTest.java
- src/test/java/org/owasp/webgoat/lessons/passwordreset/ResetLinkAssignmentTest.java
> #1396 Fix templates path for views

- src/test/resources/application-webwolf.properties
> Add fileserver location in Test

- pom.xml
- src/it/java/org/owasp/webgoat/AccessControlIntegrationTest.java
- src/it/java/org/owasp/webgoat/CSRFIntegrationTest.java
- src/it/java/org/owasp/webgoat/ChallengeIntegrationTest.java
- src/it/java/org/owasp/webgoat/CryptoIntegrationTest.java
- src/it/java/org/owasp/webgoat/DeserializationIntegrationTest.java
- src/it/java/org/owasp/webgoat/GeneralLessonIntegrationTest.java
- src/it/java/org/owasp/webgoat/IDORIntegrationTest.java
- src/it/java/org/owasp/webgoat/IntegrationTest.java
- src/it/java/org/owasp/webgoat/JWTLessonIntegrationTest.java
- src/it/java/org/owasp/webgoat/LabelAndHintIntegrationTest.java
- src/it/java/org/owasp/webgoat/PasswordResetLessonIntegrationTest.java
- src/it/java/org/owasp/webgoat/PathTraversalIntegrationTest.java
- src/it/java/org/owasp/webgoat/ProgressRaceConditionIntegrationTest.java
- src/it/java/org/owasp/webgoat/SSRFIntegrationTest.java
- src/it/java/org/owasp/webgoat/SessionManagementIntegrationTest.java
- src/it/java/org/owasp/webgoat/SqlInjectionAdvancedIntegrationTest.java
- src/it/java/org/owasp/webgoat/SqlInjectionLessonIntegrationTest.java
- src/it/java/org/owasp/webgoat/SqlInjectionMitigationIntegrationTest.java
- src/it/java/org/owasp/webgoat/WebWolfIntegrationTest.java
- src/it/java/org/owasp/webgoat/XSSIntegrationTest.java
- src/it/java/org/owasp/webgoat/XXEIntegrationTest.java
- src/main/java/org/owasp/webgoat/container/users/Scoreboard.java
> Integration test sometimes fails

- pom.xml
- src/main/java/org/owasp/webgoat/webwolf/WebSecurityConfig.java
- src/main/resources/webwolf/static/js/jwt.js
The JavaScript pointed to the context root /WebWolf/ which is no longer in use.
> fix: change url in JavaScript for JWT endpoint

- .github/dependabot.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- CREATE_RELEASE.md
- README.md
- RELEASE_NOTES.md
- pom.xml
- src/main/java/org/owasp/webgoat/lessons/challenges/Flag.java
- src/main/java/org/owasp/webgoat/lessons/challenges/FlagController.java
- src/main/java/org/owasp/webgoat/lessons/challenges/Flags.java
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge1/Assignment1.java
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge1/ImageServlet.java
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge5/Assignment5.java
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge7/Assignment7.java
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge8/Assignment8.java
- src/test/java/org/owasp/webgoat/lessons/challenges/Assignment1Test.java
> Fix release

- src/it/java/org/owasp/webgoat/ChallengeIntegrationTest.java
- src/it/java/org/owasp/webgoat/IntegrationTest.java
- src/main/java/org/owasp/webgoat/lessons/challenges/SolutionConstants.java
- src/main/java/org/owasp/webgoat/lessons/challenges/challenge7/Assignment7.java
- src/main/java/org/owasp/webgoat/webwolf/mailbox/MailboxController.java
> fix: challenge 7

- src/main/resources/lessons/hijacksession/documentation/HijackSession_content0.adoc
> Fix typo of HijackSession_content0.adoc

- .github/workflows/test.yml
> fix: Robotframework fails due to updated dependencies

- src/main/java/org/owasp/webgoat/lessons/spoofcookie/SpoofCookie.java
- src/main/java/org/owasp/webgoat/lessons/spoofcookie/SpoofCookieAssignment.java
- src/main/resources/lessons/spoofcookie/documentation/SpoofCookie_content0.adoc
- src/main/resources/lessons/spoofcookie/documentation/SpoofCookie_plan.adoc
- src/main/resources/lessons/spoofcookie/i18n/WebGoatLabels.properties
> Improve the Spoofing an Authentication Cookie lesson

- .github/workflows/release.yml
> fix: remove steps from release script

- src/main/java/org/owasp/webgoat/lessons/idor/IDORDiffAttributes.java
- src/main/java/org/owasp/webgoat/lessons/idor/IDOREditOtherProfile.java
- src/main/java/org/owasp/webgoat/lessons/idor/IDORLogin.java
- src/main/java/org/owasp/webgoat/lessons/idor/IDORViewOtherProfile.java
- src/main/java/org/owasp/webgoat/lessons/idor/IDORViewOwnProfile.java
- src/main/java/org/owasp/webgoat/lessons/idor/IDORViewOwnProfileAltUrl.java
- src/main/java/org/owasp/webgoat/lessons/idor/UserProfile.java
- src/main/resources/lessons/idor/i18n/WebGoatLabels.properties
This PR addresses multiple broken aspects of the 'Insecure Direct Object References' lesson.
> bug: Fix IDOR lesson

- src/test/java/org/owasp/webgoat/lessons/challenges/challenge7/Assignment7Test.java
- src/test/java/org/owasp/webgoat/lessons/challenges/challenge7/MD5Test.java
> Add Assignment7 Tests

- src/main/resources/webwolf/templates/fragments/header.html
> fix: WebWolf JWT jquery webjar

- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScripting.java
- src/main/java/org/owasp/webgoat/lessons/xss/stored/CrossSiteScriptingStored.java
- src/main/java/org/owasp/webgoat/lessons/xss/stored/StoredCrossSiteScriptingVerifier.java
- src/main/java/org/owasp/webgoat/lessons/xss/stored/StoredXssComments.java
- src/main/resources/lessons/xss/html/CrossSiteScriptingStored.html
- src/main/resources/lessons/xss/i18n/WebGoatLabels.properties
- src/main/resources/lessons/xss/js/stored-xss.js
> fix: Stored Cross-Site Scripting Lesson

- src/it/java/org/owasp/webgoat/XSSIntegrationTest.java
- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScriptingLesson3.java
- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScriptingLesson4.java
- src/main/java/org/owasp/webgoat/lessons/xss/CrossSiteScriptingMitigation.java
- src/main/resources/lessons/xss/i18n/WebGoatLabels.properties
> fix: XSS mitigation

- src/main/java/org/owasp/webgoat/lessons/idor/IDORViewOtherProfile.java
> fix: NPE in IDOR lesson

- src/main/resources/lessons/hijacksession/html/HijackSession.html
> fix: HijackSession lesson template deprecated Tymeleaf attribute

- src/main/java/org/owasp/webgoat/lessons/missingac/MissingFunctionACYourHashAdmin.java
- src/main/resources/lessons/missingac/i18n/WebGoatLabels.properties
> Bug fix and improve MFAC hints

- src/main/resources/lessons/cryptography/documentation/Crypto_plan.adoc
> fix: crypto basics broken links

- src/main/java/org/owasp/webgoat/lessons/xss/stored/StoredCrossSiteScriptingVerifier.java
> fix: potential NPE in the stored XSS assignment

- robot/goat.robot
- src/main/resources/webwolf/static/js/jwt.js
Detected a bug in the WebWolf JWT tool from refactoring the context paths. Added a Robot framework test
> fixed issue in JWT test tool and added robot test

- robot/README.md
- robot/goat.robot
- src/main/resources/webgoat/static/js/main.js
- src/main/resources/webgoat/templates/main_new.html
- src/main/resources/webwolf/static/js/jwt.js
> search box moved #1375 and jwt encode/decode with little delay 

- src/main/resources/webgoat/static/js/quiz.js
> fix(quiz): use $ instead of jQuery which is undefined

- src/main/java/org/owasp/webgoat/container/WebSecurityConfig.java
> feature: enable CORS configuration

- src/main/java/org/owasp/webgoat/container/lessons/Category.java
- src/main/java/org/owasp/webgoat/lessons/csrf/CSRF.java
> feat: move CSRF to A3

- .github/workflows/branchbuild.txt
- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
> chore: upgrade checkout out to v4

- .github/workflows/build.yml
- .github/workflows/pre-commit.yaml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile_desktop
- config/desktop/start_webgoat.sh
- config/desktop/start_zap.sh
- pom.xml
- src/it/java/org/owasp/webgoat/SSRFIntegrationTest.java
> update dependencies and version

- Dockerfile
- src/main/java/org/owasp/webgoat/container/WebSecurityConfig.java
> Small improvements

- src/main/java/org/owasp/webgoat/webwolf/FileServer.java
Turns out that using this method sometimes fails with an exception about unable to delete a directory. The stacktrace points to:
```
java.nio.file.FileSystemException: /tmp/webwolf-fileserver/dumbanddummer/xxe_a11.dtd: Not a directory
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[na:na]
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248) ~[na:na]
at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110) ~[na:na]
at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191) ~[na:na] …
```
> fix: copying file using `transferTo` sometimes fails.

- src/main/resources/lessons/xss/documentation/CrossSiteScripting_content4.adoc
Hi, I am a Cyber Security student using your great content and I noticed a somewhat confusingly phrased sentence in the XSS lesson text. This is the proposed fix but I am no expert so fee free to disregard!
> fix: xss lesson typo

- README.md
> Update fix version in readme

- src/it/java/org/owasp/webgoat/GeneralLessonIntegrationTest.java
- src/it/java/org/owasp/webgoat/IntegrationTest.java
We removed the constraint but did not add an extra testcase to cover this bug.
Closes: #1890
> chore: add test for solving same lesson as different user.

- src/main/java/org/owasp/webgoat/lessons/sqlinjection/introduction/SqlInjectionLesson5a.java
Students (mine anyway) don't remember the priority of AND and OR :sob:
> docs: Show boolean operators priority on `where`

- src/main/resources/lessons/passwordreset/documentation/PasswordReset_host_header.adoc
- src/main/resources/lessons/passwordreset/templates/password_reset.html
- src/main/resources/lessons/webwolfintroduction/documentation/Landing_page.adoc
> Fix password reset lesson

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile_desktop
- README.md
- pom.xml
> feat: Move to Java 23

- src/main/java/org/owasp/webgoat/container/LessonResourceScanner.java
- src/main/java/org/owasp/webgoat/container/MvcConfiguration.java
`LessonScanner.java` got removed by mistake.
Closes: gh-1992
> fix: enable resource patterns again

- src/main/java/org/owasp/webgoat/lessons/csrf/CSRFFeedback.java
> docs(CSRFFeedback.java): fixed one invalid solution about CSRF attack

- src/main/java/org/owasp/webgoat/container/assignments/AttackResult.java
- src/main/java/org/owasp/webgoat/container/assignments/AttackResultBuilder.java
- src/main/java/org/owasp/webgoat/container/i18n/Language.java
- src/main/java/org/owasp/webgoat/container/i18n/PluginMessages.java
- src/main/java/org/owasp/webgoat/container/report/LessonStatistics.java
- src/main/java/org/owasp/webgoat/container/report/ReportCardController.java
- src/main/java/org/owasp/webgoat/lessons/httpbasics/HttpBasicsQuiz.java
- src/main/resources/lessons/httpbasics/documentation/HttpBasics_content1.adoc
- src/main/resources/lessons/httpbasics/documentation/HttpBasics_content2.adoc
- src/main/resources/lessons/httpbasics/documentation/HttpBasics_plan.adoc
- src/main/resources/lessons/httpbasics/html/HttpBasics.html
- src/main/resources/lessons/httpbasics/i18n/WebGoatLabels.properties
- src/main/resources/webgoat/static/css/main.css
> Small updates and improvements in HTTP Basic lesson

- src/it/java/org/owasp/webgoat/playwright/webgoat/RegistrationUITest.java
- src/main/java/org/owasp/webgoat/container/users/RegistrationController.java
While registering a new user we forgot to log out the current user, if present.
Closes: gh-2041
> fix: register user while already logged in as other user.

- src/it/java/org/owasp/webgoat/playwright/webgoat/HttpBasicsLessonUITest.java
> chore: add test case for multiple users solving lessons

- src/main/resources/lessons/sqlinjection/js/questions_sql_injection.json
- src/main/resources/lessons/xss/js/questions_cross_site_scripting.json
> fix: rewrite questions

- docs/index.html
> chore: use webgoat.org

- src/main/resources/webgoat/templates/about.html
> chore: update about page

- src/main/resources/lessons/sqlinjection/html/SqlInjectionMitigations.html
- update the sql mitigation lessons 9 and 10 to contain the correct urls
Fixes WebGoat/WebGoat#2076
> Fixed : SQL Mitigation Broken Links - Issue 2076

- src/main/resources/lessons/chromedevtools/html/ChromeDevTools.html
Partly Resolves #2086 
This will resolve the URL for the Developer tools, URLS are case sensitive
/chromeDevTools/network => /ChromeDevTools/network 
The resolution for fixing the incomplete status requires further investigation
> 2086 Chrome Dev Tools Url

- src/main/resources/application-webgoat.properties
- src/main/resources/webgoat/templates/main_new.html
> fix: remove mailing list references
