README.txt
Include instructions for developers on how to manually deploy the project in tomcat. In particular, it wouldn't be immediate otherwise, to figure out that it is necessary to clone WebGoat-Lessons first. Otherwise the app would be stuck on the login page.
=> Instructions for manual deployment

webgoat-container/src/main/java/org/owasp/webgoat/util/LabelManagerImpl.java, webgoat-container/src/test/java/org/owasp/webgoat/util/LabelManagerImplTest.java
Issue when Tomcat is starting or stopping the session is serialized. This class caused an error because it did not implement Serializable. 
NOTE: make sure you first do a `mvn clean` before starting Tomcat again because of old session caching in the `target` directory. Maybe best to put a message on slack when this is merged.
=> Fixed not serializable error when stopping/starting Tomcat

.travis.yml, webgoat-container/pom.xml, webgoat-container/src/test/java/org/owasp/webgoat/plugins/WebGoatIT.java
On the __TravisCI__ builds, or if you run __mvn -Prun-integration-tests__ will now spawn up a tomcat an run integration tests.
Current tests only checks for login page, lessonmenu.mvc and logout page.
=> Adding headless Integration Tests with Sauce Labs

.travis.yml
Because we are using Sauce Labs, which requires a secret key to connect with the Sauce Labs server, in order to protect the secret key, this secret key is not made available to the TravisCI Virtual Machines during pull requests.
This change DISABLE the integration testing when build is triggered from a pull request.
I will try to find other ways to perform integration tests securely on pull requests, but as of know, this PR is important to keep our builds from failing.
=> Do NOT run Integration tests on pull requests

webgoat-container/src/main/webapp/WEB-INF/web.xml
This commit changes the order of the elements in the deployment descriptor so that they validate according to the XSD in Eclipse.
=> Fix #112 deployment descriptor elements in wrong order 

webgoat-container/src/main/webapp/js/goatApp/view/UserAndInfoView.js
The button in the footer was not selected by the jQuery selector. This commit adds a second selector to activate the button in the modal footer. 
The second selector was added instead of selecting all buttons inside the modal in case there will be a future wish to add some button within the modal window itself.
=> Fix #81 to activate close button in the modal footer

.travis.yml
Instead of moving the the jar and war files from target, copy these files and the target direcotry into the WEBGOAT_ARTIFACTS_FOLDER so it's all uploaded to S3
=> Copy output and target info upload to S3 folder

.travis.yml
Instead of copying jar/war artifact individually, copy the whole target folder to the "Deployable Artifacts", which will then be uploaded to Amazon S3
=> Copy whole target folder, not just individual file

.travis.yml
Coverity is a cloud static code analysis tool, free for open-source projects. Enable scan submissions from travis CI
=> Test enable Coverity SAST

.travis.yml
By cleaning before tbe cobertura goal, this was removing the exec.jar and the war file.
=> Do not clean before mvn cobertura and coveralls

.travis.yml, pom.xml, webgoat-container/src/main/java/org/owasp/webgoat/application/WebGoatServletListener.java
1. Update versions of dependencies and plugins except Spring and JavaEE
2. Upon Travis.CI build, export the build number that will be used by our About page
3. Tomcat complained about a SEVERE issue about the h2 driver not being released upon process termination. Now, upon contextDestroyed(), check for driver versions loaded in thes context so we can unregister them
=> Update dependency version, build number and unregister DB driver

webgoat-container/pom.xml
The Eclipse import failed due to different that default lifecycle phase.
=> #66 Fixing jar plugin lifecycle issue

README.MD
WebGoat does not endorse any specificy Static Code Analysis Vendor, so removing Coverity Badge in order not to send mixed messages
=> Remove Coverity Badge from README

pom.xml
In order to specify which key to use for signing the JAR/WAR, add the keyname configuration under the Release Profile on the Parent Pom
=> Setting GPG keyname as WebGoat in Parent Pom

pom.xml
In order to push it to The Maven Central Repository, adding the OSSRH repo under distributionManagement on the Parent Pom
=> Adding OSSRH Repository on Parent Pom

pom.xml
Fixed when `mvn -install` is executed in WebGoat-Lessons it will create a zip and upload it.
This project will unzip it during a `mvn -Prelease ........` and place the jars in the plugin_lessons directory.
This should automate the release process.
=> webgoat-container should unpack all the lessons #192

webgoat-container/src/main/webapp/WEB-INF/webgoat.properties
Unable to reproduce the issue in #181 so this commit re-enables the lesson.
=> Enable weak authentication cookie lesson 

webgoat_developer_bootstrap.sh
The code of the script uses bash syntax (e.g. [[  ]] tests) while the header refers to sh. For systems where sh is not a syslink to bash it's better to make the shabang explicit.
C.
=> Fix shebang

webgoat-container/src/main/java/org/owasp/webgoat/service/LabelDebugService.java, webgoat-container/src/main/java/org/owasp/webgoat/service/PluginReloadService.java, webgoat-container/src/main/java/org/owasp/webgoat/session/LabelDebugger.java, webgoat-container/src/main/webapp/WEB-INF/pages/main_new.jsp, webgoat-container/src/main/webapp/css/main.css, webgoat-container/src/main/webapp/js/goatApp/controller/LessonController.js, webgoat-container/src/main/webapp/js/goatApp/model/LabelDebugModel.js, webgoat-container/src/main/webapp/js/goatApp/model/PluginReloadModel.js, webgoat-container/src/main/webapp/js/goatApp/view/DeveloperControlsView.js, webgoat-container/src/main/webapp/js/goatApp/view/GoatRouter.js, webgoat-container/src/test/java/org/owasp/webgoat/session/LabelDebuggerTest.java
Adds developer control option to the user menu. The controls can be shown/hidden from there.
The controls allow for reloading plugins which then causes a page reload. They also allow enabling/disabling of label highlighting for translation.
Once we have #194 in place, this should be revisited so the plugin reload does not reload from the start but rather reload the same page.
This also fixes #216.
=> Developer controls

README.MD, webgoat_developer_bootstrap.sh
Commit Message:
- Use '-e' option in script echo commands to enable interpretation of escape sequences -> to make bash colours work
- README changed to show proper execution instruction
Script -> Bash colours aren't going to appear without '-e' option to interpret escape sequences.
README -> Can't rely on /bin/sh to symlink to /bin/bash, e.g. some distros will have it link to /bin/dash which doesn't accept -e as a echo option so the color output will fail. Either way, it's unnecessary as the script has the appropriate shebang declaration to be simply run with ./webgoat_developer_bootstrap.sh
=> Updates to Dev Bootstrap

webgoat-container/src/main/java/org/owasp/webgoat/i18n/ExposedReloadableResourceMessageBundleSource.java, webgoat-container/src/main/java/org/owasp/webgoat/i18n/LabelProvider.java, webgoat-container/src/main/java/org/owasp/webgoat/service/LabelService.java, webgoat-container/src/test/java/org/owasp/webgoat/util/LabelProviderTest.java
**Fixes**  #265
This is a basic implementation for a **LabelService**, which can be used by the UI to fetch all labels in order to implement i18n on the client.
If no language is specified in the request, the service checks the locale in the request header and takes that instead. If everything else fails, it will just provide the labels of the fallback language.
In order to do this, I had to extend the **ReloadableResourceBundleMessageSource**, as the built-in **MessageSource** doesn't support retrieving all messages at once.
I also fixed a small bug in **LabelProvider**, which always used the fallback language, even if the given language was supported.
**Testing:**
The Service is accessible at **service/labels.mvc** after logging in (if the labels should be fetched before login, there …
=> Issue #265: Created LabelService to support UI localization

webgoat-container/src/main/java/org/owasp/webgoat/AsciiDoctorTemplateResolver.java
Fixes #293 
Adds an option to the asciidoc renderer with the suggested fix of using the **xhtml** backend, which renders images in a way thymeleaf is happy with.
(I didn't check in the cat though ;))
=> Issue #293: fix images in asciidoc by setting backend to xhtml

webgoat-container/src/main/java/org/owasp/webgoat/AsciiDoctorTemplateResolver.java, webgoat-container/src/main/resources/static/css/coderay.css, webgoat-container/src/main/resources/templates/main_new.html, webgoat-lessons/sql-injection/src/main/resources/plugin/SqlInjection/lessonPlans/en/SqlInjection_content9.adoc
Fixes #275 
This PR activates `source-highlighting` with **coderay**, which is the standard in **asciidoctorj**.
Depending on which one gets merged first, there might be a merge-conflict between this and #294, as they both introduce attributes for the `AsciiDoctorTemplateResolver`.
So now if you use `[source,java]` for a code-snippet in a `.adoc` template, it should be syntax-highlighted.
The snippet in the issue works now, I only had to switch the quotes, because they were somehow invalid:
=> Issue #275: Activate Syntax Highlighting with Coderay in Asciidoc

README.MD, webgoat-container/pom.xml, webgoat-container/src/main/docker_rpi3/Dockerfile
Hi,
since the currently build container cannot be used on a Raspberry Pi I've extended the current project. 
Therefore I've added a new Dockerfile and extended _web-container_'s `pom.xml`. Documentation how to use the changes have been added to the `README.md`. 
I'm not sure if the solution to use a property to decide wether to build the container or ARM or not is the best - if it's not just give me a hint how to solve it properly.
=> Added support to build an Docker container to run it on Raspberry Pi

README.MD
- Removed unnecessary white space
- Included the instructions for what path in the URL to go to once the app starts
- Added instructions for different types of docker use (boot2docker and docker-machine)
=> Updated the instructions for running on Docker

webgoat-lessons/bypass-restrictions/pom.xml, webgoat-lessons/bypass-restrictions/src/main/java/org/owasp/webgoat/plugin/BypassRestrictions.java, webgoat-lessons/bypass-restrictions/src/main/java/org/owasp/webgoat/plugin/BypassRestrictionsFieldRestrictions.java, webgoat-lessons/bypass-restrictions/src/main/java/org/owasp/webgoat/plugin/BypassRestrictionsFrontendValidation.java, webgoat-lessons/bypass-restrictions/src/main/resources/html/BypassRestrictions.html, webgoat-lessons/bypass-restrictions/src/main/resources/i18n/WebGoatLabels.properties, webgoat-lessons/bypass-restrictions/src/main/resources/lessonPlans/en/BypassRestrictions_FieldRestrictions.adoc, webgoat-lessons/bypass-restrictions/src/main/resources/lessonPlans/en/BypassRestrictions_FrontendValidation.adoc, webgoat-lessons/bypass-restrictions/src/main/resources/lessonPlans/en/BypassRestrictions_Intro.adoc, webgoat-lessons/html-tampering/pom.xml, webgoat-lessons/html-tampering/src/main/java/org/owasp/webgoat/plugin/HtmlTampering.java, webgoat-lessons/html-tampering/src/main/java/org/owasp/webgoat/plugin/HtmlTamperingTask.java, webgoat-lessons/html-tampering/src/main/resources/html/HtmlTampering.html, webgoat-lessons/html-tampering/src/main/resources/i18n/WebGoatLabels.properties, webgoat-lessons/html-tampering/src/main/resources/lessonPlans/en/HtmlTampering_Intro.adoc, webgoat-lessons/html-tampering/src/main/resources/lessonPlans/en/HtmlTampering_Task.adoc, webgoat-lessons/insecure-login/pom.xml, webgoat-lessons/insecure-login/src/main/java/org/owasp/webgoat/plugin/InsecureLogin.java, webgoat-lessons/insecure-login/src/main/java/org/owasp/webgoat/plugin/InsecureLoginTask.java, webgoat-lessons/insecure-login/src/main/resources/html/InsecureLogin.html, webgoat-lessons/insecure-login/src/main/resources/i18n/WebGoatLabels.properties, webgoat-lessons/insecure-login/src/main/resources/js/credentials.js, webgoat-lessons/insecure-login/src/main/resources/lessonPlans/en/InsecureLogin_Intro.adoc, webgoat-lessons/insecure-login/src/main/resources/lessonPlans/en/InsecureLogin_Task.adoc, webgoat-lessons/pom.xml, webgoat-server/pom.xml
I remade WebGoat 7.1 lessons for HTML tampering, bypassing javascript validation and sniffing HTTP requests. There are some changes, for example no disabled field in front-end restrictions lesson, because I haven't figured out how to request a parameter for validation that hasn't been there. Also, the lesson for HTML tampering ("buying the TV in online store") is slightly altered, so that the lesson is not passed on update of the cart but actual buying of the TV.
=> Basic lessons for WebGoat 8, as seen in WebGoat 7

webgoat-images/vagrant_provision.sh
Fixes an error while installing Google Chrome:
```
Failed to fetch http://dl.google.com/linux/chrome/deb/dists/stable/Release 
Unable to find expected entry 'main/binary-i386/Packages' in Release file
(Wrong sources.list entry or malformed file)  
Some index files failed to download.  
They have been ignored, or old ones used instead.
```
See https://askubuntu.com/questions/724093/no-more-updates-for-google-chrome-apt-get-update-error
=> Fix Apt Error for Google Repository

webgoat-lessons/auth-bypass/src/main/resources/lessonPlans/en/bypass-intro.adoc
This fixes some spelling issues in the bypass intro lesson
=> Chore - fix spelling issues in bypass intro lesson

webgoat-container/src/main/resources/static/js/goatApp/model/LessonContentModel.js
This fixes the next page button when the current url doesn't end with the page number like in http://localhost:8080/WebGoat/start.mvc#lesson/IDOR.lesson
=> Fix next page button when url doesn't end with page number

webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/plugin/StoredXssComments.java, webgoat-lessons/cross-site-scripting/src/main/resources/i18n/WebGoatLabels.properties, webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content5b.adoc, webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content6a.adoc
This PR fixes some spelling errors in the lesson about XSS.
It also reverses the order of how comments are displayed during the last part of the lesson, so that newest comments are shown on top. This is not as intuitive but it mitigates the problem that a user might create a comment containing invalid HTML, which prevents all following comments from being rendered. With the order reversed the user can still add new comments to complete the task.
=> Small fixes for lesson about XSS

webgoat-lessons/sql-injection/src/main/java/org/owasp/webgoat/plugin/mitigation/SqlInjectionLesson12a.java
See #505 for the issue description.
In this lesson, you have to perform SQL injection in the `ORDER BY` clause. By making a case distinction, you are supposed to find out what the IP is of the `webgoat-prd` server. But if you submit it, WebGoat just checks if you filled in the IP of any of the servers in the database instead of the specific IP of `webgoat-prd`.
Fixed this by adding the hostname to the where clause.
=> Fix SQL injection mitigation answer (fixes #505)

scripts/build_docker.sh
Encapsulating the `WEBGOAT_HOME` variable in quotes allows for spaces to exist in the path
=> encapsulated the WEBGOAT_HOME in quotes

webgoat-container/src/main/java/org/owasp/webgoat/MvcConfiguration.java, webgoat-lessons/xxe/src/test/java/org/owasp/webgoat/plugin/BlindSendFileAssignmentTest.java
As I was interested in contributing, I started by cloning the repository and trying to build all code.
I found that there are unit test failures when the OS language is not English and when port 9090 is used. 
In this pull request, I made a change to the i18n set up of WebGoat so it will not fall back to default OS language. Which I think is the intended idea and solves that unit test failure.
In the XXE module, a hardcoded port number was used for the unit test, which can fail the build if the port is used. I changed this to take a dynamically available port.
With these two changes the unit tests all work.
=> unit test related fixes for i18n and available ports

webgoat-lessons/challenge/src/main/java/org/owasp/webgoat/plugin/Flag.java
#568 
findOne changed to findByUser to fix the bug when trying to post the flag. 
The bug is caused by findOne which expects the type of the ID field which is Long and not String
=> fix for posting the Flag bug

webgoat-lessons/chrome-dev-tools/src/main/resources/lessonPlans/en/ChromeDevTools_Assignment_Network.adoc, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/plugin/DOMCrossSiteScripting.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/plugin/DOMCrossSiteScriptingVerifier.java
Small fix for the Chrome Developer Tool lesson.
If you do not run the javascript first, but immediately enter a result, a Nullpointer was triggered and no "incorrect result" was shown. 
Magic_num was changed to NetworkNum as is used in the exercise.
System.out.println is removed
=> Fix chrome tool lesson

webgoat-lessons/password-reset/src/main/resources/html/PasswordReset.html
Somehow exercise 6 had an incorrect link to the ForgotPassword.
/WebGoat/PasswordReset/reset/create-password-reset-link
was changed to /WebGoat/PasswordReset/ForgotPassword/create-password-reset-link
in the html so it matches the service
=> password-reset forget link corrected to avoid 404

webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/plugin/CSRFGetFlag.java, webgoat-lessons/csrf/src/main/resources/html/CSRF.html
In CSRF-3 use POST instead of GET  to prevent solving the assignment just by opening the URL in a new tab.
=> Do not allow trivial solution to CSRF-3

docker-compose-postgres.yml
I really don't know why exactly spring parameters are not used here,
probably for schema creation step. Until changing what the application does on startup
this will make it 'just work' without extra changes.
=> add login&pwd in JDBC url for PostgreSQL docker compose

webgoat-lessons/http-proxies/src/main/resources/lessonPlans/en/HttpBasics_ProxyIntro5.adoc, webgoat-lessons/http-proxies/src/test/java/org/owasp/webgoat/plugin/HttpBasicsInterceptRequestTest.java
From the existing task description it took me a while to figure out that I should send the `changeMe` parameter via the query string (it might be obvious because GET requests typically don't have an HTTP body though technically they could).
The second commit I'm not sure about (that's why it's a separate commit which I can quite easily remove). But I wondered why the URL is different to the other test case.
=> Improve intercept lesson

webgoat-server/pom.xml, webgoat-server/src/test/java/org/owasp/webgoat/General_TestHelper.java, webgoat-server/src/test/java/org/owasp/webgoat/SqlInjectionAdvanced_TestHelper.java, webgoat-server/src/test/java/org/owasp/webgoat/SqlInjectionMitigation_TestHelper.java, webgoat-server/src/test/java/org/owasp/webgoat/SqlInjection_TestHelper.java, webgoat-server/src/test/java/org/owasp/webgoat/TestHelper.java, webgoat-server/src/test/java/org/owasp/webgoat/WebGoatIntegrationTest.java
This change adds an integration test for some of the basic lessons and sql lessons. It can be used as part of the pipeline, or in your ide or against your environment that you want to test. 
It can help in detecting if the lesson still works when stuff is refactored.
Downside is that it would contain information to solve the lessons. But that is more or less the same information that can be found from the code or unit tests.
The test run locally as part of mvn clean install but could also be run after deploying and starting the application using additional -D system properties.
=> integration tests for (some) lessons

webgoat-container/src/main/java/org/owasp/webgoat/users/UserService.java
Fixes the issue #642 
Solution:
Check if the User exists, before adding the User. If so the User will still be updated, but no additional tracker will be added.
=> Fixed #642 - multiple tracker for one user fixed

pom.xml, webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/plugin/CSRFFeedback.java
This change forces the user to post valid JSON to WebGoat in the CSRF-7 lesson.
As `objectMapper.readValue` parses also invalid JSON, the lesson is currently a bit easier than intended.
=> Make lesson csrf-7 stricter (do not allow invalid JSON, e.g. trailing =)

webgoat-container/src/main/java/org/owasp/webgoat/lessons/Assignment.java, webgoat-container/src/main/java/org/owasp/webgoat/service/LessonMenuService.java, webgoat-container/src/main/java/org/owasp/webgoat/service/LessonProgressService.java, webgoat-container/src/main/java/org/owasp/webgoat/session/WebSession.java, webgoat-container/src/test/java/org/owasp/webgoat/service/LessonMenuServiceTest.java, webgoat-container/src/test/java/org/owasp/webgoat/service/LessonProgressServiceTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/GeneralLessonTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/XSSTest.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson3.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson4.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson5a.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingLesson6a.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/CrossSiteScriptingQuiz.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/DOMCrossSiteScripting.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/DOMCrossSiteScriptingVerifier.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/mitigation/CrossSiteScriptingMitigation.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/stored/CrossSiteScriptingStored.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/stored/StoredCrossSiteScriptingVerifier.java, webgoat-lessons/cross-site-scripting/src/main/java/org/owasp/webgoat/xss/stored/StoredXssComments.java, webgoat-lessons/cross-site-scripting/src/main/resources/html/CrossSiteScripting.html, webgoat-lessons/cross-site-scripting/src/test/java/org/owasp/webgoat/xss/StoredXssCommentsTest.java
Even after completing all assignments, the lesson could never be completed. Two assignments have been marked deprecated and disabled by removing the RestController. The other lessons have been moved to separate packages. Now with a clean database the lesson can be seen as completed.
=> XSS lesson completion fixes

webgoat-container/src/main/java/org/owasp/webgoat/AsciiDoctorTemplateResolver.java, webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/OperatingSystemMacro.java, webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/WebGoatTmpDirMacro.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/GeneralLessonTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/JWTLessonTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/PasswordResetLessonTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/XXETest.java, webgoat-lessons/xxe/src/main/java/org/owasp/webgoat/xxe/SimpleXXE.java, webgoat-lessons/xxe/src/main/resources/i18n/WebGoatLabels.properties, webgoat-lessons/xxe/src/main/resources/lessonPlans/en/XXE_blind_assignment.adoc, webwolf/src/main/java/org/owasp/webwolf/FileServer.java
This contains changes to be able to test in combination with running applications without known temp directories. And the extra services are used to provide better examples in the hints and doc page. And a change to test it using https. So i could verify the xxe test on windows. default remains http.
=> xxe path info

webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/JWTLessonTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/SqlInjectionMitigationTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/WebWolfTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/XSSTest.java, webgoat-lessons/webwolf-introduction/src/main/java/org/owasp/webgoat/webwolf_introduction/LandingAssignment.java, webgoat-lessons/webwolf-introduction/src/main/resources/templates/webwolfPasswordReset.html, webwolf/pom.xml, webwolf/src/main/java/org/owasp/webwolf/requests/Requests.java, webwolf/src/main/java/org/owasp/webwolf/requests/WebWolfTraceRepository.java, webwolf/src/main/resources/application-webwolf.properties
It seems that Spring Boot 2 upgrade no longer traces POST parameters of HTTP requests. So for the first lesson where that is used, I decided to change the template to use a GET in stead. Also the initial first link was broken. (Results from doing the workshop today)
=> working version with fixed link and GET for tracing purposes

webgoat-container/pom.xml, webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/OperatingSystemMacro.java, webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/WebGoatTmpDirMacro.java, webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/WebGoatVersionMacro.java, webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/WebWolfMacro.java, webgoat-lessons/challenge/src/main/resources/html/Challenge1.html, webgoat-lessons/challenge/src/main/resources/lessonPlans/en/Challenge_introduction.adoc, webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content5b.adoc, webgoat-lessons/http-proxies/src/main/resources/lessonPlans/en/HttpBasics_ProxyIntro4.adoc
small enhancement for asciidoc. So links can easily be directed to a new tab. 
And added the Challenge page to the first challenge lesson. This was related to the comment on the link to the scoreboard being incorrect (hardcoded to localhost). Now it is a relative link that opens in a separate tab.
=> upgrade ascii doc with support for link in new tab

webgoat-container/src/main/java/org/owasp/webgoat/users/UserForm.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/CSRFTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/XXETest.java, webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/csrf/CSRFFeedback.java, webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/csrf/CSRFGetFlag.java, webgoat-lessons/csrf/src/main/java/org/owasp/webgoat/csrf/CSRFLogin.java, webgoat-lessons/csrf/src/main/resources/html/CSRF.html
Some parts of the lesson were broken. The 8th assignment is also a bit strange. Part of the data in the session is moved to the new session. The web goat user data is then no longer in sync with the actual user principal of the request. For the lesson I now check on the user principal which is more correct anyway. But maybe something to look at. All CSRF lessons are ok now.
The length of the username had to be enlarged due to the csrf-...... uuid length.
=> CSRF lesson fixes and added integration test

webgoat-lessons/idor/src/main/java/org/owasp/webgoat/idor/IDORViewOwnProfile.java
In the migration to Spring 2, this method lost its get mapping to the… IDOR/profile url,breaking the javascript call to that address.
=> Broken IDOR lesson due to lost URL

webgoat-container/src/main/java/org/owasp/webgoat/asciidoc/WebWolfMacro.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/IntegrationTest.java, webgoat-integration-tests/src/test/java/org/owasp/webgoat/PasswordResetLessonTest.java, webgoat-lessons/password-reset/src/main/java/org/owasp/webgoat/password_reset/ResetLinkAssignmentForgotPassword.java
I have made a few small changes to support the use of running webgoat and webwolf in a docker stack/compose way. It still works standalone as well and in normal docker containers.
See #731 related issue. I ran all the integration tests on the a docker image from the build in this branch. I can deliver the goat.yml docker stack/compose file once these changes are on the develop branch and a release has been made, so I can refer to a webgoat image with the required fixes.
The docker swarm yel can be found here: https://github.com/zubcevic/webgoat-training/tree/master/docker-swarm
In this yaml a timezone is added so the Deserialization exercise can be made successful. And hostnames are defined so that the XXE and password reset calls from the goat container to the web wolf container are …
=> Hostname through proxy and docker

webgoat-lessons/pom.xml
This lesson is intended to show the dangers of outdated dependencies. However in version 1.4.7 of xstream, the vulnerability is fixed! In 1.4.5 it is still present, so I suggest this downgrade. It is tested and works as intended, just as 1.4.7 does not.
=> Solves issue 725

README.MD, docker-compose.yml, goat-with-reverseproxy.yaml, webgoat-server/Dockerfile
Changes to the Readme. It proposes to use the all in one docker image. This still needs to be part of the release process, but at least one image is pushed to web goat/goatandwolf repository. It solved the issue with the working directory and the timezone issue.
It also includes the advanced docker stack deploy example where you would be able to use it with fake hostsnames and port 80 through a reverse proxy. Which will become available after we push the latest working image to webgoat/webgoat-8.0 repo.
=> dockerfile and compose changes

webgoat-lessons/crypto/src/main/resources/lessonPlans/en/signing.adoc
Some of the changes correct simple misspellings. Some are intended to clarify or simplify the language.
=> Correct typos and clarify language in signing.adoc

webgoat-container/src/main/resources/static/js/goatApp/view/LessonContentView.js
With this small change in the javascript, a 403 return on a challenge will be shown in the feedback section. This is useful/necessary if for demo purposes, you want to show the effect of a web application firewall protecting your insecure web app. You might want to challenge people if they can still misuse the vulnerability in these situations.
=> add support for status 403 feedback from e.g. ModSecurity/CRS

webgoat-lessons/crypto/src/main/java/org/owasp/webgoat/crypto/CryptoUtil.java, webgoat-lessons/crypto/src/main/resources/i18n/WebGoatLabels.properties
While checking the lesson, I noticed some lack of info in the hints and also saw that base64 with some linefeeds or spaces were not excepted without giving proper feedback
=> corrected hints and improved error handling base64

webgoat-container/src/main/resources/static/css/quiz.css, webgoat-container/src/main/resources/static/js/quiz.js, webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content1.adoc
The quiz assignments in CIA, SQL Injection Advanced and XSS were no longer visible in the UI. Due to a move that took place in commit 6c25cf8e433db70aab9a1785f5331165adc914c3 of March 3rd.
This one adds the quiz.css and quiz.js back in the webgoat-container as all quiz assignments still expect this location.
For the rest a small fix to use the script console in stead of the address bar in the first XSS assignment.
=> Xss fix change

webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content3.adoc, webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_content6.adoc, webgoat-lessons/csrf/src/main/resources/lessonPlans/en/CSRF_Login.adoc, webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content10.adoc, webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content11.adoc, webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content12.adoc, webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content9.adoc, webgoat-lessons/webgoat-introduction/src/main/resources/lessonPlans/en/Introduction.adoc
On windows all characters would be normal with the -Dfile.encoding=UTF-8, but just to support or prevent reports on issues with Cp1252, some characters have been replaced so they will be ok in Cp1252 as well.
=> lessonplan character updates so it also works on Windows Cp125

webgoat-lessons/jwt/src/main/resources/lessonPlans/en/JWT_refresh.adoc
Fixes some minor spelling issues in the Refreshing a token section of the JWT tokens lesson.
=> JWT_refresh.adoc: Fix spelling issues

webgoat-lessons/password-reset/src/main/resources/lessonPlans/en/PasswordReset_SecurityQuestions.adoc, webgoat-lessons/password-reset/src/main/resources/lessonPlans/en/PasswordReset_host_header.adoc, webgoat-lessons/password-reset/src/main/resources/lessonPlans/en/PasswordReset_password_reset_link.adoc
Fixes spelling issues in PasswordReset_SecurityQuestions.adoc and PasswordReset_host_header.adoc.  Also removes unused file 'PasswordReset_password_reset_link.adoc".
=> Password reset lesson related cleanup

webgoat-lessons/secure-passwords/src/main/java/org/owasp/webgoat/secure_password/SecurePasswordsAssignment.java
- When solving the solution (entering a correct password) then the 'Score: 4/4' does not start on a new line, instead it is glue to the Estimated cracking time line. As a solution the </br> is added as a suffix on that line (and successive lines).
- Maximum score is 4, not 5 (see also the assignment, and https://github.com/nulab/zxcvbn4j/blob/master/src/main/java/com/nulabinc/zxcvbn/TimeEstimates.java#L23 which is the origin of getScore() )
=> SecurePasswordsAssignment: Fix output formatting

webgoat-lessons/idor/src/main/resources/lessonPlans/en/IDOR_intro.adoc
The closing ')' in the URL was not taken up in the link causing a 404 when clicking the URL.
=> IDOR_intro.adoc: Fix 404

webgoat-lessons/cross-site-scripting/src/main/resources/lessonPlans/en/CrossSiteScripting_quiz.adoc
The original URL was malformed because it contained a closing ) which did not end up in the link. However the corrected link performs a redirect to the link provided in this patch.
=> XSS Quiz: Fix 404

webgoat-lessons/vulnerable-components/src/main/resources/lessonPlans/en/VulnerableComponents_content5.adoc
This was discussed in ticket https://github.com/WebGoat/WebGoat/issues/724 however the Dinis Cruz Blog remains available through a blogspot.com URL which might be more interesting to reference than an web.archive.org link.
=> Dinis Cruz Blog

webgoat-lessons/http-proxies/src/main/resources/lessonPlans/en/1proxysetupsteps.adoc
Fix typo in `brower` -> `browser`
=> Fix a typo in 1proxysetupsteps.adoc

webgoat-container/src/main/java/org/owasp/webgoat/users/Scoreboard.java, webgoat-container/src/main/resources/static/css/main.css, webgoat-container/src/main/resources/static/js/goatApp/templates/scoreboard.html, webgoat-container/src/main/resources/templates/scoreboard.html
This pull request intends to make the challenge scoreboard look more the same as the regular look and feel and to show the results in an ordered ranking. The numbering starts from 1 for the one with the most flags captured. See screenshot
=> layout of page improved and ordered ranking

README.MD, webgoat-container/src/main/java/org/owasp/webgoat/service/LessonMenuService.java, webgoat-container/src/main/resources/application-webgoat.properties, webgoat-container/src/test/java/org/owasp/webgoat/service/LessonMenuServiceTest.java
Here is a solution for customising the categories and lessons. See the updated Readme for instructions on starting with Java, and here is how you would do it in a docker container: 
docker run -d -p 80:8888 -p 8080:8080 -p 9090:9090 -e TZ=Europe/Amsterdam -e EXCLUDE_CATEGORIES="CLIENT_SIDE,GENERAL,CHALLENGE" -e EXCLUDE_LESSONS="SqlInjectionAdvanced,SqlInjectionMitigations" webgoat/goatandwolf:latest-test
It will look like:
By default only the Client side challenges are no longer shown. They can be enabled if you provide a category with none e.g.
EXCLUDE_CATEGORIES=none
=> Custom menu

.gitignore, pom.xml
This plugin is added in order to still be able to build individual modules. It comes along with the use of the ${revision}
=> flattened pom plugin added for easy build of seperate modules

webgoat-lessons/sql-injection/src/main/resources/lessonPlans/en/SqlInjection_content6.adoc
Fix SQL Injection line comments issue.
Issue:
```
Example: SELECT * FROM users WHERE name = 'admin' --AND pass = 'pass'
```
Should be:
```
Example: SELECT * FROM users WHERE name = 'admin' -- AND pass = 'pass'
```
=> Fix SQL Injection line comments issue.

.mvn/wrapper/maven-wrapper.properties
The version of Maven is not compatible with the plugin "org.codehaus.mojo:flatten-maven-plugin:1.2.5" used in webgoat-container
```
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] Copying 111 resources
[INFO] The encoding used to copy filtered properties files have not been set. This means that the same encoding will be used to copy filtered properties files as when copying other filtered resources. This might not be what you want! Run your build with --debug to see which files might be affected. Read more at https://maven.apache.org/plugins/maven-resources-plugin/examples/filtering-properties-files.html
[INFO] ------------------------------------------------------------------------ …
```
=> Update Apache Maven from 3.2.1 to 3.2.5

webgoat-lessons/jwt/src/main/resources/i18n/WebGoatLabels.properties
The hints for JWT used `jwt` instead of `JWT` which makes it difficult to solve the lesson as the hint actually points someone in the wrong direction.
Resolves: #123
=> Fix typo in hints

webgoat-lessons/insecure-deserialization/src/main/resources/lessonPlans/en/InsecureDeserialization_SimpleExploit.adoc, webgoat-lessons/ssrf/src/main/resources/lessonPlans/en/SSRF_Intro.adoc, webgoat-lessons/ssrf/src/main/resources/lessonPlans/en/SSRF_Prevent.adoc, webgoat-lessons/ssrf/src/main/resources/lessonPlans/en/SSRF_Task2.adoc
The link pointed to the old OWASP website. Also fixed some typos here and there
Resolves: #1136
=> Fix link and typo

docker/Dockerfile
With the refactoring of the Dockerfile, the two lines required for anonymous rootless user conditions also disappeared. 
With the two statements back in place, webgoat/webwolf can also run on Openshift.  (The current webgoat/goatandwolf:latest does not work, the webgoat/goatandwolf:openshift made from this branch does work)
=> openshift support

.github/workflows/branch_build.yml, .github/workflows/pr_build.yml, .github/workflows/release.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> Set permissions for GitHub actions

src/it/java/org/owasp/webgoat/LabelAndHintIntegrationTest.java, src/main/resources/i18n/messages.properties, src/main/resources/i18n/messages_nl.properties, src/main/resources/lessons/vulnerable_components/i18n/WebGoatLabels.properties, src/main/resources/webgoat/templates/login.html, src/main/resources/webgoat/templates/registration.html
This fixes one duplicate label key issue (Go!) and makes the register and login page fully customisable. Only fully implemented for English and Dutch, but at least is shows that it can be done.
The LabelAndHintIntegration test now also fails if labels in a language other than English are defined and not provided in English.
=> i18n fix and improvement for login and register page

src/main/resources/lessons/vulnerablecomponents/documentation/VulnerableComponents_content5a.adoc
The name is
org.owasp.webgoat.lessons.vulnerablecomponents.Contact not
org.owasp.webgoat.vulnerablecomponents.Contact
=> Update interface name to exploit

src/main/java/org/owasp/webgoat/lessons/jwt/JWTVotesEndpoint.java, src/test/java/org/owasp/webgoat/lessons/jwt/JWTVotesEndpointTest.java
When the admin json element passes as a `boolean`:
```
{
"admin": true
}
```
the parsing is now successful.
=> Support `boolean` when parsing the token.

.github/workflows/build.yml, README.md
The documentation now contains a description to reuse the initially create container. This way the user can start where they left off. The documentation only described creating a new container each and every time leaving users to create a new login each and every time.
=> Add documentation about reusing the container.

pom.xml
I added a independent optional profile for running the coverage report. It may be interesting if we want to know our code coverage.
It can be executed with:
`mvn verify -Pcoverage`
The report is available in the `target/site` directory.
I tested all on my side and it's working, but @nbaars , @zubcevic  , please, one of you, as I added a little change in the surefire plugin, please can you take a look and check that it's also working on your side?
Thanks!
=> Add coverage profile

src/main/java/org/owasp/webgoat/lessons/ssrf/SSRFTask1.java, src/main/java/org/owasp/webgoat/lessons/ssrf/SSRFTask2.java
Hello!
While reading WebGoat's code, I saw that `String.matches()` is used while forgetting that it accepts a regex. 
For SSRF Task 1, this is not really an issue by looking at the code, but for SSRF Task 2, an actual SSRF could be done, albeit to a domain that matches the regex, and with extra DNS magic steps on the target/target infrastructure.
I used `ipconfig/pro` as an example, and as you can imagine, we can also think about `ipconfiggpro` or others.
My suggestion is to escape the dot.
Here are illustrative examples:
```java  
System.out.println((new String("images/jerry/png")).matches("images/jerry.png"));
// true
System.out.println((new String("images/jerry/png")).matches("images/jerry\\.png"));
// false
System.out.println((new …
```
=> Add SSRF Regex restrictions

README.md
Hi, I noticed that commands in README.md are from the previous version. And I decided to fix this minor issue. 
Thanks!
=> doc: fix version strings

pom.xml, src/main/resources/webwolf/templates/fragments/header.html
Update to make dependencies utilize the locator, ensuring WebJar is version-agnostic.
Solves #1567
=> WebWolf: Make webjar dependencies version agnostic

src/main/resources/lessons/sqlinjection/db/migration/V2019_09_26_1__servers.sql
Hello, 
With my students as exercise, we also retrieved with a blind sql injection the `id` of the `webgoat-prd` and we were surprised to discover that the id was the same as the id of the `webgoat-pre-prod`.
To be realistic, the `id` of `webgoat-prd` should be `5` for example.
=> fix: servers id

.github/workflows/branchbuild.yml, .github/workflows/build.yml, pom.xml
First change to allow local compilation and test with JDK21
Build and release should still remain on Java17 for now
A branch build workflow is added to test code changes when still in a local or remote branch
=> Java 21 initial support

robot/goat.robot, src/main/java/org/owasp/webgoat/webwolf/jwt/JWTToken.java
There is some optimization that could be done in regards to the javascript and how many times the decode function is called. For now it is more safe to skip the validation
=> skip validation for JWT

config/desktop/WebGoat.txt
You can see that the file goes with the underscore 
https://github.com/WebGoat/WebGoat/blob/88a321c268e88dee06d19ed6a276d1012257853c/config/desktop/start_webgoat.sh
=> fix: typo in WebGoad.txt

src/main/resources/lessons/httpbasics/documentation/HttpBasics_content2.adoc, src/main/resources/lessons/httpbasics/html/HttpBasics.html
In this exercise, there is a confusion: because the sentences use a past tense, users tend to search for the answers in the HTTP requests of the previous exercise. But the way to solve this exercise is to post the form once, look at the HTTP verb and posted body and then answer and submit again.
IMHO, the it is much clearer now...
=> fix: texts to avoid confusion

src/main/resources/lessons/bypassrestrictions/documentation/BypassRestrictions_FieldRestrictions.adoc, src/main/resources/lessons/xss/documentation/CrossSiteScripting_content4.adoc
There are actually five fields in this exercise (and attempting the exercise using only 4 of the fields will not validate it).
Regards
=> fix: typos in texts

src/main/resources/lessons/missingac/html/MissingFunctionAC.html
This fixes 2 issues:
1. there are 3 links but the exercise expects 2 answers so it is confusing for users
2. the links href start with "/" so they are broken if Webgoat is deployed to a subfolder (e.g. `mysite.com/webgoat`)
Thanks!
=> Fix hidden links in MissingFunctionAC.html.

src/main/resources/lessons/sqlinjection/documentation/SqlInjection_content13.adoc
Hi, in SQL `CASE` must end with `END` keyword.
* [case specification](https://hsqldb.org/doc/2.0/guide/dataaccess-chapt.html#N1300F)
```
CASE
case specification
<case specification> ::= <simple case> | <searched case>
<simple case> ::= CASE <case operand> <simple when clause>... [ <else clause> ] END
<searched case> ::= CASE <searched when clause>... [ <else clause> ] END 
```
=> fix: typo in SQLi blind case

Dockerfile, Dockerfile_desktop
Current syntax now used to denote the "WebGoat team" as maintainer
Link: https://docs.docker.com/reference/dockerfile/#label
=> build(Dockerfile): replace deprecated MAINTAINER tag with label of the same

src/main/resources/lessons/httpbasics/documentation/HttpBasics_plan.adoc
docs: minor: fix broken link OWASP ZAP - use official website link https://www.zaproxy.org/ ([src](https://fr.wikipedia.org/wiki/OWASP_ZAP))
It seems that ZAP is not directly published under OWASP website now but has it's own domain.
broken link:  https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project
(sorry for the branch name I initiate this PR with github UI. I'll do better branch name next time).
=> Update HttpBasics_plan.adoc - https://www.zaproxy.org/

src/main/java/org/owasp/webgoat/lessons/sqlinjection/introduction/SqlInjectionLesson9.java, src/main/resources/lessons/sqlinjection/i18n/WebGoatLabels.properties, src/test/java/org/owasp/webgoat/lessons/sqlinjection/introduction/SqlInjectionLesson9Test.java
Hello,
Some students succeed the `SQL (intro) > lesson 9` by updating all the salaries of employees!
With this update it's no more possible ; I also changed the behavor of the response :
* the data returned are always the data employees ordered by `salary desc` (confidentiality injection remain in the previous lesson)
* the injection is commited only in success case
* employees data remain clear
* solutions too for all students
and of course:
* this pull request will not pass the current `SqlInjectionLesson9Test` :stop_sign: 
* but the updated test class  `SqlInjectionLesson9Test`  yes :ok: 
```
./mvnw test -Dtest="org.owasp.webgoat.lessons.sqlinjection.introduction.SqlInjectionLesson9Test"
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] …
```
=> fix: Success if only Smith earn most salary

src/main/java/org/owasp/webgoat/lessons/sqlinjection/introduction/SqlInjectionLesson5a.java, src/main/resources/webgoat/static/js/goatApp/view/LessonContentView.js
1. exercice forms are not reset on success, so user can see why he successed
1. exercice forms are reset  when resetting lesson
1. quizzes colors are removed  when resetting lesson (fix)
=> "fix": reset form and quiz color on reset lesson

src/main/resources/i18n/messages.properties, src/main/resources/webgoat/static/js/goatApp/view/HintView.js
Regardless of the presence of localized label for the hint button, when toggling the button, default hardcoded text would be displayed.
In the `toggleLabel` function in `HintView.js`, `polyglot` is used to translate the hint labels rather than using hardcoded texts.
The hint button correctly shows the localized labels for the hint button and falling back to the English version if it is absent.
Fixes #1944
=> fix: Hint labels showing default text regardless of localization

src/main/java/org/owasp/webgoat/container/LessonTemplateResolver.java, src/main/resources/lessons/challenges/html/Challenge1.html, src/main/resources/lessons/challenges/html/ChallengeIntro.html
The name of the html now matches the name of the lesson class. This PR also removes the introduction text from challenge 1
Closes: gh-2069
=> fix: challenge introduction page loads

src/main/resources/application-webgoat.properties
Not necessary to have this enabled while running WebGoat. Only helpful for development.
=> chore: comment out script generation
